### ISSUE TITLE
jscoverage_report is not defined error

### ISSUE THREAD

**Issue by pillal** [tntim96/JSCover#138]
Hi,

I modified WebDriverGeneralProxyTest.java to run my application by changing 
webClient.get("http://tntim96.github.io/JSCover/example/"); to the URL I'd like to run on. I commented out the rest of the shouldRunExampleAndStoreResultProgrammatically() function except for         ((JavascriptExecutor) webClient).executeScript("jscoverage_report('no-frames');");

I get the following error which reads...
jscoverage_report is not defined. 

Could you let me know how this issue can be fixed?

**Comment by mayankdevapplift** [comment]
I am also facing the same issue and I am accessing url with ssl enabled

**Comment by tntim96** [comment]
JSCover's proxy doesn't support SSL.
