### ISSUE TITLE
How to find the Code coverage of a web application hosted by IIS server through JScover

### ISSUE THREAD

**Issue by vipindubey84** [tntim96/JSCover#174]
Hi All,

I have to get the coverage of devlopment code(Java script) through our UI automated scripts written in c# (Selenium WebDriver) for an web application hosted via an IIS server.

Can you please guide me in this regards.

**Comment by tntim96** [comment]
There are two basic techniques:
1. Pre-instrument the JavaScript with JSCover file-mode before running your tests
2. Configure your tests to run through JSCover in proxy mode

The first option can be more reliable and will work over SSL (JSCover can't proxy SSL requests). There is an example of the basic technique [here](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system) in the examples.

**Comment by vipindubey84** [comment]
Hi Team,
It is really very great to have your fast response. I really appreciate it.

I have followed the first option suggested by you.I am listing the steps which i followed to instrument java script code.
1) First i installed  web application which need to tested(After installing it all .js files get stored in some folder say Build)
 2) Now i ran StartServer.bat which instrumented the ,js files under Build Folder.

As per my understanding, JSCover work with instrumented file so i replaced the Build Folder(Original .JS files) content with the generated instrumented file.

Since the web application runs the java scripts inside build folder so if i am putting the instrumented file instead of actual java script files, My Web application is only not launching.

Please find the image of StartServer.bat attached.
![startserver](https://cloud.githubusercontent.com/assets/10398698/5627147/ac176082-95ba-11e4-8683-bd388f99ec5b.jpg)

**Comment by tntim96** [comment]
It looks like you're using an old version (0.2.3). The latest is [1.0.16](http://sourceforge.net/projects/jscover/files/JSCover-1.0.16.zip/download)

**Comment by vipindubey84** [comment]
Hello Team...

Please see the steps which i am performing for JScoverage server file mode. Please suggest if i am doing something wrong.

1)My web page is served by IIS server  as "https://localhost" and all js files are residing at location c:\\inetpub\\wwwroot after installing the application Setup.

2)By usiing JScover file server method if i take all jScode(code inside thsese folder--c:\\inetpub\\wwwroot) and instrument it to some other loaction(Say Jscover Folder structuctre as per your example) and try launching my web page "https://localhost"  the web page is opening but there is no coverage shown.

3) since step 2 was not giving coverage, so i took the generated instrumented files from instrumented folder  and replaced it with c:\\inetpub\\wwwroot. but in this case my webpage "https://localhost" itself is not opening.

Please guide me if i am making anything wrong here.
I need to implement the coverage for my project.

I tried using Proxy method but it doesnot work:(
Can i use Proxy  method for Https Web pages????

**Comment by vipindubey84** [comment]
Hello Team...

Please see the steps which i am performing for JScoverage server file mode. Please suggest if i am doing something wrong.

1)My web page is served by IIS server as "https://localhost" and all js files are residing at location c:\inetpub\wwwroot after installing the application Setup.

2)By usiing JScover file server method if i take all jScode(code inside thsese folder--c:\inetpub\wwwroot) and instrument it to some other loaction(Say Jscover Folder structuctre as per your example) and try launching my web page "https://localhost" the web page is opening but there is no coverage shown.

3) since step 2 was not giving coverage, so i took the generated instrumented files from instrumented folder and replaced it with c:\inetpub\wwwroot. but in this case my webpage "https://localhost" itself is not opening.

Please guide me if i am making anything wrong here.
I need to implement the coverage for my project.

I tried using Proxy method but it doesnot work:(
Can i use Proxy method for Https Web pages????

**Comment by tntim96** [comment]
> i took the generated instrumented files from instrumented folder and replaced it with c:\inetpub\wwwroot

That's correct.

> in this case my webpage "https://localhost" itself is not opening

Can you check the following:
1. Does `jscover.log` contain any errors after instrumenting the files
2. When you load the page, do you get any JavaScript errors?

> Can i use Proxy method for Https Web pages?

Not currently.
