### ISSUE TITLE
HTTPS support for proxy mode

### ISSUE THREAD

**Issue by cavaIV** [tntim96/JSCover#175]
Please consider extending the HTTP proxy functionality to also enable HTTPS communications.

We would highly appreciate this new functionality because JSCover could then be added seeminglessly in our web regression test stack.

**Comment by tntim96** [comment]
Have you tried just instrumenting the JavaScript on the file-system? This is generally the preferred method, requires no proxy-configuration on the browser, and has less performance impact (and works on HTTPS).

There is an example of the basic technique [here](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system) in the examples.

**Comment by cavaIV** [comment]
Thank's for the quick answer, I am going to try this now. 

Is there an easy way to tell JSCover to merge all actions that were done via JavaScript automatically in the mode that you linked

**Comment by tntim96** [comment]
Do you mean collate all the coverage data? The linked example above will do that. The coverage data between page loads is temporarily stored in HTML5 local storage to achieve this.

**Comment by cavaIV** [comment]
We use Selenium Grid where a number of browser instances (Selenium WebDriver) are started in parallel for each test run. They then each perform different system tests and are closed afterwards. 

I am trying to merge/collate all the different code coverage data after such a test run where many test cases have been executed. Is this doable with JSCover as you described?

**Comment by tntim96** [comment]
Yes. Each run can save a separate report (this can be done programmatically which is also done in the linked example). The documentation merging reports is [here](http://tntim96.github.io/JSCover/manual/manual.xml#reportMerging).
