### ISSUE TITLE
How to find the Code coverage of a web application hosted by IIS server through JScover for https site

### ISSUE THREAD

**Issue by vipindubey84** [tntim96/JSCover#176]
Hello Team...

Please see the steps which i am performing for JScoverage server file mode for code coverage . Please suggest if i am doing something wrong.

1)My web page is served by IIS server as "https://localhost" and all js files are residing at location c:\inetpub\wwwroot after installing the application Setup.

2)By usiing JScover file server method if i take all jScode(code inside thsese folder--c:\inetpub\wwwroot) and instrument it to some other loaction(Say Jscover Folder structuctre as per your example) and try launching my web page "https://localhost" the web page is opening but there is no coverage shown.

3) since step 2 was not giving coverage, so i took the generated instrumented files from instrumented folder and replaced it with c:\inetpub\wwwroot. but in this case my webpage "https://localhost" itself is not opening.

Please guide me if i am making anything wrong here.
I need to implement the coverage for my project.

I tried using Proxy method but it doesnot work:(
Can i use Proxy method for Https Web pages????

**Comment by vipindubey84** [comment]
I have open new issue as i was not able to edit the issue#174

**Comment by tntim96** [comment]
> i took the generated instrumented files from instrumented folder and replaced it with c:\inetpub\wwwroot

That's correct.

> in this case my webpage "https://localhost" itself is not opening

Can you check the following:
1. Does `jscover.log` contain any errors after instrumenting the files?
2. When you load the page, do you get any JavaScript errors?

> Can i use Proxy method for Https Web pages?

Not currently.
