### ISSUE TITLE
JSCover-all.jar merge limits

### ISSUE THREAD

**Issue by lanzelot1989** [tntim96/JSCover#178]
Where do you see the limit of the --merge functionality for reports?

I am trying to merge about 1900 test cases and I always get stuck with a Java OOM exception:
* Caused by: java.lang.OutOfMemoryError: Java heap space

I tried to merge only 100 test cases at a time and afterwards merge those subresults which also did not  work.
Furthermore, I tried to increase the heap space for Java to up to 1024MB.

**Comment by tntim96** [comment]
Is it possible to put the `jscoverage.json` JSON files somewhere for me to investigate?

**Comment by tntim96** [comment]
You can try the fix from source, [the latest drone.io build](https://drone.io/github.com/tntim96/JSCover/files)
 or the [maven snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/tntim96/JSCover/1.0.17-SNAPSHOT/). For maven you'll need to add sonatypes repository with:
```xml
        <pluginRepository>
            <id>Sonatype repository</id>
            <name>Sonatype's Maven repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
```

**Comment by lanzelot1989** [comment]
**Thanks a lot!**

This seems to work really great for us, I can now merge 2000 - 4000 test cases with about 700MB of memory now.

I am sure I could merge even more now, but I haven't tested that.
