### ISSUE TITLE
Add Proxy support

### ISSUE THREAD

**Issue by Shnitzelil** [tntim96/JSCover#180]
We're working in isolated environment and would like to enable proxy configuration

**Comment by tntim96** [comment]
There is already proxy support. Take a look at the [manual](http://tntim96.github.io/JSCover/manual/manual.xml#gettingStartedProxy) and [examples](https://github.com/tntim96/JSCover/tree/master/examples/proxy) and [samples project](https://github.com/tntim96/JSCover-samples/tree/master/src/test/java/jscover/webdriver/proxy).

NB: Usually instrumenting the JS on the file-system is a better approach as it will work over SSL and has less of a performance impact.

**Comment by Shnitzelil** [comment]
Thank you for your quick answer, but I think you didn't understand my
request.

In addition to the proxy mode I need to configure the JSCover to chain to
next proxy.

In other words JSCover need to "know" where is my proxy as now JSCover is
in the middle :) :)

Thanks

On Tue, Jan 20, 2015 at 12:43 AM, tntim96 <notifications@github.com> wrote:

> There is already proxy support. Take a look at the manual
> <http://tntim96.github.io/JSCover/manual/manual.xml#gettingStartedProxy>
> and examples
> <https://github.com/tntim96/JSCover/tree/master/examples/proxy> and samples
> project
> <https://github.com/tntim96/JSCover-samples/tree/master/src/test/java/jscover/webdriver/proxy>
> .
>
> NB: Usually instrumenting the JS on the file-system is a better approach
> as it will work over SSL and has less of a performance impact.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tntim96/JSCover/issues/180#issuecomment-70574469>.
>



-- 
Kobi Gana קובי גנה

**Comment by tntim96** [comment]
DId you try configuring a [SOCKS|http://docs.oracle.com/javase/7/docs/technotes/guides/net/proxies.html]

**Comment by Shnitzelil** [comment]
Thanks again for the quick answer.
I already tried this solution, despite I knew it probably will not work...
but thanks for your suggestion :)
Any other ideas?

On Tue, Jan 20, 2015 at 12:51 PM, tntim96 <notifications@github.com> wrote:

> DId you try configuring a [SOCKS|
> http://docs.oracle.com/javase/7/docs/technotes/guides/net/proxies.html]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tntim96/JSCover/issues/180#issuecomment-70636147>.
>



-- 
Kobi Gana קובי גנה

**Comment by tntim96** [comment]
There has to be a clear path forward to re-open and mark as an enhancement. I don't know why the JVM level solution using SOCKS failed (do you know why?), and I'm not sure how this could be elegantly implemented using HTTP proxies as JSCover uses sockets in it's proxy implementation.

I think you best bet is to instrument the JS before deploying. While it may be slightly inconvenient, it solves all these connection problems.

**Comment by Shnitzelil** [comment]
Hey,

Don't have any clue why the SOCKS solution failed, but I previously tried
it (and also via the Java console in the Windows Control Panel).

Didn't test it but I would try first
jscover.server.ProxyService.get(jscover.server.HttpRequest) in line 492

Instead of HttpURLConnection conn = (HttpURLConnection) url.openConnection()

My unpolished suggestion is:

        Proxy proxy = Proxy.NO_PROXY;
        String chainedProxy = System.getProperty("chainedProxy");
        if (chainedProxy != null) {
            String[] proxyDetails = chainedProxy.split(":");
            InetSocketAddress socketAddress =
InetSocketAddress.createUnresolved(proxyDetails[0],
Integer.parseInt(proxyDetails[1]));
            proxy = new Proxy(Proxy.Type.HTTP, socketAddress);
        }
        HttpURLConnection conn = (HttpURLConnection)
url.openConnection(proxy);


If this make sense I will provide fine solution with input validation and
so on...



On Tue, Jan 20, 2015 at 11:38 PM, tntim96 <notifications@github.com> wrote:

> There has to be a clear path forward to re-open and mark as an
> enhancement. I don't know why the JVM level solution using SOCKS failed (do
> you know why?), and I'm not sure how this could be elegantly implemented
> using HTTP proxies as JSCover uses sockets in it's proxy implementation.
>
> I think you best bet is to instrument the JS before deploying. While it
> may be slightly inconvenient, it solves all these connection problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tntim96/JSCover/issues/180#issuecomment-70739055>.
>



-- 
Kobi Gana קובי גנה
