### ISSUE TITLE
Server mode deny external connection

### ISSUE THREAD

**Issue by Shnitzelil** [tntim96/JSCover#181]
Hey,

We're using JSCover in Server mode but recently we tried to access to the server from other machine.
My guess is that the JSCover listen to the localhost. is it possible to add option to listen to all interfaces (e.g. 0.0.0.0)?

**Comment by tntim96** [comment]
The relevant code in WebDaemon is
```Java
serverSocket = new ServerSocket(configuration.getPort());
```
...which under the hood calls
```Java
  public ServerSocket(int port) throws IOException {
    this(port, 50, (InetAddress)null);
  }
```
...which has [documentation](http://docs.oracle.com/javase/7/docs/api/java/net/ServerSocket.html#ServerSocket(int,%20int,%20java.net.InetAddress)):

> If bindAddr is null, it will default accepting connections on any/all local addresses

Can you double check?

**Comment by Shnitzelil** [comment]
You're absolutely right, if you use null it should listen to all local
address. Sadly I was failed to access to JSCover in Server mode from remote
machine.
I'll continue to investigate this from my side and update you.

Thanks

On Thu, Jan 29, 2015 at 11:14 PM, tntim96 <notifications@github.com> wrote:

> The relevant code in WebDaemon is
>
> serverSocket = new ServerSocket(configuration.getPort());
>
> ...which under the hood calls
>
>   public ServerSocket(int port) throws IOException {
>     this(port, 50, (InetAddress)null);
>   }
>
> ...which has documentation
> <http://docs.oracle.com/javase/7/docs/api/java/net/ServerSocket.html#ServerSocket(int,%20int,%20java.net.InetAddress)>
> :
>
> If bindAddr is null, it will default accepting connections on any/all
> local addresses
>
> Can you double check?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tntim96/JSCover/issues/181#issuecomment-72105286>.
>



-- 
Kobi Gana קובי גנה

**Comment by tntim96** [comment]
Thanks for the update
