### ISSUE TITLE
JSCover proxy and html5 websockets?

### ISSUE THREAD

**Issue by nikolauskrismer** [tntim96/JSCover#183]
I just integrated jscover into my selenium integration testing tasks. With the jscover proxy this works quite good since I did not need to change the generated web files at all. Thanks for this great feature :+1: 

However, there is one thing that does not work: websockets.
So I just wanted to ask if there is a configuration switch (or something alike) that makes my websockets work with the jscover proxy (maybe something like a proxy bypass configuration for the websocket protocol).

**Comment by tntim96** [comment]
Proxying long lived connections isn't currently supported - to do so would be difficult and probably require a specialized 3rd party library. Generally it's easier, although it may not seem so at first, to instrument the JavaScript before running the tests.

> if there is a configuration switch (or something alike) that makes my websockets work with the jscover proxy (maybe something like a proxy bypass

Not currently. A proxy bypass is usually configured at in the browser. If you can think of a reasonable mechanism for solving your issue I'd be happy to add it.

**Comment by nikolauskrismer** [comment]
I know that it is rather easy to instrument the js files...   
If I remember correctly there is even a grunt task for that.

There is one reason I do not want to instrument the files before testing and that is that I'd need to duplicate all my files into a "js/instrumented" directory. That would brake all my links made in js files (for example the base directory set in config file of requirejs). If this isn't true please correct me... in fact instrumenting would help me a lot (especially to simplify the build process itself... since no starting of a proxy server would be needed :-))

The solution I was thinking about is to add proxy excludes pattern. One could for example exclude the url "http://localhost:8080/myApp/websocket" from being routed through the proxy server (maybe by adding an exlude to "^/myApp/websocket$"), which would make websockets work again.

**Comment by tntim96** [comment]
> The solution I was thinking about is to add proxy excludes pattern

...but that would be done in the client/browser not the proxy (so can't be done in JSCover).

> I'd need to duplicate all my files into a "js/instrumented" directory...in fact instrumenting would help me a lot (especially to simplify the build process itself

How about an option to instrument the JS files in place?

**Comment by nikolauskrismer** [comment]
IMHO inplace js file replacement is a bad idea.
Since I really use the tested war on production servers all files on these servers would be instrumented.
I was thinking about adding uninstrumented and instumented files to that war and switching between them by using HTTP GET Parameter, but that could cause the problems of broken links (as stated before)...

In fact that's the great thing about the proxy mode:
You can test the war files that are used in production but do not need to modify them.

I am not really sure if the exclude pattern should be configured in the browser. After some searching through the web I found out that browsers allow bypassing of hosts, not of urls (isn't it). So maybe the option should be indeed added to the proxy. Something similar is done by the firefox addon "FoxyProxy"

**Comment by nikolauskrismer** [comment]
I switched to instrumented file mode now, so that I can use websockets.
In fact I did not find it easy to do at all. In combination with my other tools (grunt for building, requirejs for AMD, and many more) there were quite some problems (some of them are still not solved very beautifully, but this is not the fault of jscover).

The beauty if the file system mode in jscover is that really only files that should be covered are covered (no third party js files like google maps api). However, as stated above there are also some downsides of this solutions (at least for me => I had to add some files to the tested war files, so that there are now some files in production wars which should not be there - or there neeeds to be an additional build steps to remove the instrumented files again -> but then my jscoverage get parameter switch won't work anymore :-)).

However, for me the problem is solved by now.
But maybe this is a more general problem so a solution should be implemented for websockets.

**Comment by tntim96** [comment]
> The beauty if the file system mode in jscover is that really only files that should be covered are covered (no third party js files like google maps api)

Proxy-mode will respect the `--no-instrument` options to allow exclusion 3rd party libraries.

> However, for me the problem is solved by now.

That's great.

**Comment by ElodieVandromme** [comment]
I got the same issue : I configure my environment to get coverage of my selenium tests on my application using JSCover in proxy mode. That works fine until I have to use WebSocket.
Is there any development in the support of websocket by the proxy mode or should I switch to instrumented file mode ?

Thanks.

**Comment by tntim96** [comment]
I would recommend swapping to file mode
