### ISSUE TITLE
How to measure JavaScript code coverage using JSCover & with Selenium UI tests?

### ISSUE THREAD

**Issue by montoyo4me** [tntim96/JSCover#185]
Hi Tim,

Below is my scenario,
1. I am having FitNesse UI test cases developed using Java (eClipse) & Selenium libraries
2. tomcat is running on a linux box
3. From my windows box I want to run these fitnesse UI test cases which will run in any of the browser and generate code coverage report.

I am looking for is a step by step instruction to generate JS code coverage. Any help will be deeply appreciated.
I went through http://tntim96.github.io/JSCover/ for this but couldn't make out perfect solution or rather I confused.

Thanks

**Comment by tntim96** [comment]
I don't know to much about FitNesse. I'll take a look but it might be worth posting a question on that project.

**Comment by montoyo4me** [comment]
With command line I can execute these FitNesse test cases.

**Comment by montoyo4me** [comment]
Hi tntim96,

Have you got a chance to work on this?

**Comment by tntim96** [comment]
I haven't had time to check out FitNesse in detail, but I think the key is to instrument the JS before running the tests, use JSCover's HTML5 localStorage to save coverage between page loads, and put a hook in at the end of your test to save the coverage data.

Take a look at the [localStorage-file-system example](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system).

**Comment by bianxirui** [comment]
If the web could not work well locally to be instrumented before running the test, what's the alternative choice?

**Comment by tntim96** [comment]
I'm not sure what you mean. If you are limited to testing on a server, instrumenting the JS before-hand is generally the best choice.
