### ISSUE TITLE
JS boolean operators used for defaults show up as untested branches

### ISSUE THREAD

**Issue by wrschneider99** [tntim96/JSCover#188]
If you have something like 

`var foo = bar || {} `

then it will show up as an uncovered branch - expression `bar || {} ` never evaluates to false.  The boolean `||` operator is used as a substitute for `bar ? bar : {}`.

**Comment by tntim96** [comment]
Is `--detect-coalesce` (Try to exclude coalesce assignments from conditional coverage) what you're after?

**Comment by wrschneider99** [comment]
Yes, that's probably what I'm looking for.  Didn't notice it in the docs because I didn't know the word for that kind of statement.
