### ISSUE TITLE
jvmRegularExpressions

### ISSUE THREAD

**Issue by saur5784** [tntim96/JSCover#189]
I dont see this link working.
Can you give a quick exammple as how to use regexp as param in proxy mode.
I want to instrument only certain packages.

**Comment by tntim96** [comment]
Do you mean http://tntim96.github.io/JSCover/manual/manual.xml#jvmRegularExpressions? It should work in Chrome - in FireFox or IE, put the cursor in the address bar after the page has loaded and hit enter again. It should link to section `3.1.3 Java Regular Expressions`.

**Comment by tntim96** [comment]
Do you mean http://tntim96.github.io/JSCover/manual/manual.xml#jvmRegularExpressions? It should work in Chrome - in FireFox or IE, put the cursor in the address bar after the page has loaded and hit enter again. It should link to section `3.1.3 Java Regular Expressions`.

**Comment by saur5784** [comment]
Thank you. Btw, you mention that JSCover's server mode works on Windows 7. Does this mean it works only on Win7 or are other platforms like MAC/Linux supported ?

**Comment by tntim96** [comment]
It works on all platforms that run Java, which is pretty much any system. [The original, JSCoverage server, doesn't work well on Windows 7](http://siliconforks.com/jscoverage/bugs/30).
