### ISSUE TITLE
jscoverage_report

### ISSUE THREAD

**Issue by saur5784** [tntim96/JSCover#190]
What does ((JavascriptExecutor) driver).executeScript("jscoverage_report('"
					+ reportSubDir + "');");
this returns ?
I want to halt my driver and code until, the script is done executing. Is there a return value that I can look for ?

Thanks.

**Comment by tntim96** [comment]
It returns the request response text, which isn't very useful - I may change that. The code will block until the code is executed, so you shouldn't need to inspect the response.

**Comment by saur5784** [comment]
Can you please do that...I run this on a seperate thread so need to check that return value.

**Comment by tntim96** [comment]
If there is any string returned, then your code has worked. The report throws an exception if anything went wrong.
