### ISSUE TITLE
JSCover as remote server

### ISSUE THREAD

**Issue by saur5784** [tntim96/JSCover#191]
Can I run JSCover on a remote machine and then use its IP-address to instrument my code and collect coverage or it has to be localhost.
I am trying it, and it hangs when I click on SummaryTab. Please help.

Thanks.

**Comment by tntim96** [comment]
In web-server mode it runs as a web-server so sure, you can run it on a different machine to the browser.

If it hangs on the summary tab then something else is wrong. You would need to start looking in the logs to see what is going on.

**Comment by saur5784** [comment]
I did try it and nothing gets logged in logs other than starting
jscover...iv log level as info...i dont see any code getting instrumented
either but it works fine when i run it as proxy.

**Comment by tntim96** [comment]
The web-server mode and proxy mode do different things. The web-server mode is for serving up an existing JS based test suite like Jasmine or QUnit, whereas proxy mode is for measuring code-coverage for a browser based test suite that hits the application server directly.

**Comment by saur5784** [comment]
Oh didnt realize that...so in order to get code coverage for my selenium
tests...proxy mode is the only viable option!

**Comment by tntim96** [comment]
You can also use file-mode to pre-instrument the JS on your application server, and while they may take some effort, it if often worth it.

**Comment by saur5784** [comment]
Yes but with ci/cd it will be a big issue...proxy mode works well on my
localhost but issues im getting into are with ci/cd on saucelabs and others
thus wanted to leverage a strght remote server solution.
Thanks a lot though for ur response and developing this tool!

**Comment by bianxirui** [comment]
>The web-server mode is for serving up an existing JS based test suite like Jasmine or QUnit, whereas proxy mode is for measuring code-coverage for a browser based test suite that hits the application server directly.

if we want to get coverage report through our test suite of webdriver, we could only choose proxy mode?

**Comment by tntim96** [comment]
Yes, however you can also use file-mode. It's usually harder to set up, but worth it.
