### ISSUE TITLE
No-Instrument seems to be faulty.

### ISSUE THREAD

**Issue by saur5784** [tntim96/JSCover#195]
Starting proxy server using : "--no-instrument=analytics.js",
But I continue to see this in logs : 
20150514 16:06:21.342,11510,SEVERE,"/analytics.js",jscover.server.ProxyService,
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at jscover.server.ProxyService.handleProxyRequest(ProxyService.java:379)
	at jscover.server.ProxyService.handleProxyGet(ProxyService.java:368)
	at jscover.server.InstrumentingRequestHandler.handleGet(InstrumentingRequestHandler.java:475)
	at jscover.server.HttpServer.run(HttpServer.java:416)

**Comment by tntim96** [comment]
I might need some more information to determine what's going on. IS there anyway for me to replicate this?

BTW, to avoid these sort of issues you could try pre-instrumenting the JS as shown in [this example](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system).

**Comment by saur5784** [comment]
Can not use pre-instrumenting because the code is constantly changing/emerging....Yea you wont be able to replicate it...Is there any reason why I am seeing "Connection timed out: connect" ?
Also, I tried using --no-instrument-reg="/angular*" and it was still instrumenting angular*.js files...?
Thanks again..

**Comment by tntim96** [comment]
> Can not use pre-instrumenting because the code is constantly changing/emerging....

Is it possible to add a server-side filter to do this then? I'd be happy to help incorporate any code required if that would help.

> Also, I tried using --no-instrument-reg="/angular" and it was still instrumenting angular.js files

Try escaping the forward slash (e.g. `--no-instrument-reg=\\/angular.js`). At the very least `--no-instrument-reg=.*angular.js` should work.

Also, make sure the expression after `--no-instrument-reg=` matches the path (or at the least a sub-string of the start of the path) for angular.js as it appears in the jscover report. You should also be able to see what's instrumented or skipped via logging.

**Comment by saur5784** [comment]
Well it will be great if we can get https working for proxy-mode.
Also, I did try using --no-instrument-reg=angular*.js but it keeps on
instrumenting the angular1.3.0002.js file and bombing out on SEVERE
exception.

**Comment by tntim96** [comment]
> I did try using --no-instrument-reg=angular*.js

That is an Ant-type pattern, not a [regular expression](http://docs.oracle.com/javase/6/docs/api/java/util/regex/Pattern.html). Try `--no-instrument-reg=.*angular.*`.

>  it will be great if we can get https working for proxy-mode.

I have no plans to implement this soon as I'm not aware of any open-source tools that would make this simple. Pre-instrumenting the JS on the server avoids this and several other issues. If that's not possible, as stated above, try doing the instrumentation in your web-server - are you using a Java server (e.g. Tomcat , Jetty or something using the servlet spec.)? Again I'm happy to help with this integration if it would help.
