### ISSUE TITLE
How to ignore comma break when counting code lines?

### ISSUE THREAD

**Issue by wahaha2001** [tntim96/JSCover#196]
Dear all,

Our source code used lots of object properties, like below :

var record = {     //this line was count as covered.
	maintitle: "testDocs",     //this line was not count as covered.
	subtitle: "The Guide",      //this line was not count as covered.
	forall: "All",    //this line was not count as covered.
	author: {    //this line was not count as covered.
		firstname: "xxxx",     //this line was not count as covered.
		surname: "xxxx"    //this line was not count as covered.
	} 
}; 

So by now each property will be count as a new line,  but even our UT covered the declare statement,  only the first line will be counted as covered, the rest lines were counted as not-covered.

Any way to not count comma in object body as line break but count the whole object body as covered if the object was used?

Thanks.

**Comment by tntim96** [comment]
> So by now each property will be count as a new line

It shouldn't be. The coverage JSON for the above script when run is:

```JSON
{"/script.js":{"lineData":[null,1]}}
```

...which means there's one line and it was hit once. Can you double-check.
