### ISSUE TITLE
How to deploy to have jscover work in inverted mode?

### ISSUE THREAD

**Issue by bianxirui** [tntim96/JSCover#200]
Hi, I'm Lareina, fresh in web test.

Our web application is a https web that could not run in iFrame containing a mass of .js files. How could we deploy our files to get code coverage report in “inverted mode”? From manual I know we should add window.open('path/to/jscoverage.html'); to regular test page, however, is the total JSCover-all.jar needed to deploy?

In short， assume I am the QA of web site: https://jquery.com which is running inside a Weblogic server like ours. If I want to get the JavaScript code coverage of this site by JSCover, what's your suggested steps to do so?（WebDriver is preferred）
BTW, are there any conflicts between inverted mode and local storage mode so that only one mode is allowed?

Thanks a lot!

**Comment by tntim96** [comment]
I would recommend pre-instrumenting the JS in file-mode so that your server is serving the instrumented JS and using `--local-storage`. With `--local-storage` you won't needed any frames or inverted mode. There is an example of this technique [here](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system).

**Comment by bianxirui** [comment]
Are the pre-instrumentation means working in file system?
Are following commands enough to complete the pre-instrumentation:
>java -jar target/dist/JSCover-all.jar -fs --local-storage doc/example target/example

**Comment by tntim96** [comment]
> Are the pre-instrumentation means working in file system?

Yes

> Are following commands enough to complete the pre-instrumentation?

For that example, yes. Check [the file-mode documentation](http://tntim96.github.io/JSCover/manual/manual.xml#fileMode) for other features you may want to use.

**Comment by bianxirui** [comment]
If I close jscoverage.html after click "open in window", then operated in my page, couldn't I get the coverage report, right?

**Comment by tntim96** [comment]
If you inspect and run at the example linked to above, you'll see you don't need jscoverage.html at all unless you want to view the report with JSCover.

The ruby example runs:
```ruby
coverageJSON = @driver.execute_script('return jscoverage_serializeCoverageToJSON();')
```
...then saves that in `jscoverage.json`. That can be converted to LCOV or cobertura XML, or combined with the JSCover files (`jscoverage.js`, `jscoverage.html` etc...) to view the report.

**Comment by bianxirui** [comment]
but our application should work at server mode rather than file system, could I get report without jscoverage.html open?

**Comment by tntim96** [comment]
> assume I am the QA of web site: https://jquery.com which is running inside a Weblogic server like ours...what's your suggested steps to do so

Going back to the start of our conversation, file-mode will work, and you don't need jscoverage.html if you also use `--local-storage`.

**Comment by bianxirui** [comment]
but where could we find the report if we set >--report-dir=target ?

**Comment by bianxirui** [comment]
```java -jar target/dist/JSCover-all.jar -ws --local-storage --document-root=doc/example --report-dir=target```
is my start command, if I type```http://localhost:8080/home.html```directly in browser, could I get jscoverage report at ```/target```?

**Comment by tntim96** [comment]
The `-ws` is server mode. You need to use `-fs` for file mode. Please review the [file-mode documentation](http://tntim96.github.io/JSCover/manual/manual.xml#fileMode) and the [localStorage-file-system example](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system). Please make sure you can run this example which demonstrates a simple example of what you need to do.

**Comment by bianxirui** [comment]
but our application have to work at web server..
what about ```-ws --proxy --port=8080``` instead of ```-ws```

**Comment by tntim96** [comment]
That won't work. The example does what you're trying to do. Please try to run the example.

The `file-mode` terminology is probably confusing, but it is used to pre-instrument the JS which will be served by your web-logic server. Try instrumenting one JS file to get started.
