### ISSUE TITLE
Store tab not showing if I load jscoverage.html from my webserver

### ISSUE THREAD

**Issue by haitao80** [tntim96/JSCover#203]
I instrumented the JS files and load jscoverage.html within my application serever.  The coverage works perfect.  The only thing is that the Store tab does not show.

If I load jscoverage.html from JSCover web server, the Store tab shows.  But I cannot get any coverage data.

Any suggestion will greatly appreciated!

**Comment by tntim96** [comment]
That's easily solved. You can call the JavaScript function `jscoverage_serializeCoverageToJSON()` and store the results to a file called `jscoverage.json` which can then be converted to Cobertura XML, LCOV, or viewed directly with accompanying JSCover report files (e.g. `jscoverage.html`, `jscoverage.js` - NB the file mode generated `jscoverage.js` needs `jscoverage_isReport = true;` appended to view the report).
