### ISSUE TITLE
Please add example usages for only-instrument-reg

### ISSUE THREAD

**Issue by binodpanta** [tntim96/JSCover#204]
Doc improvement request: the usage doc on only-instrument-reg says regexp, but I am pulling my hair out on this, since it seems quite sensitive to the string I pass, and often fails if it is not property formed, I have no clue what format is supported and what is not, based on the doc

**Comment by tntim96** [comment]
How about I add a feature that allows this to be tested from the command line. Something like:
`-reg-test <regular expression> <URL path>` which returns whether there was a match or not?

**Comment by binodpanta** [comment]
Ok sure that will be fine too. Thanks. I will also go refer to the regex links you posted.

**Comment by tntim96** [comment]
I've addressed that in https://github.com/tntim96/JSCover/issues/206.

You can test with the JAR at https://drone.io/github.com/tntim96/JSCover/files, or in Maven using 1.21-SNAPSHOT with:
```xml
<repositories>
    <repository>
        <id>Sonatype repository</id>
        <name>Sonatype's Maven repository</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```
