### ISSUE TITLE
Memory leak in jscover?

### ISSUE THREAD

**Issue by binodpanta** [tntim96/JSCover#207]
I have been running some tests using jsCover 1.0.18 and noted that jscover does not seem to be releasing memory. I had a run that ran 10 minutes or so, and I found jscvoer reached about 5GB committed memory after which is started throwing out of memory.

We call the the snapshot code like this after each test,

collect:
jscover_json = (String) je
                    .executeScript("return jscoverage_serializeCoverageToJSON();");

then post the data using the POSt like this later

post:
        String requestURL = "http://" + pageURL.getHost() + ":"
                + pageURL.getPort() + "/jscoverage-store/" + identifier;

Is there a way to ask JSCover to 'reset'/'release' all its data, and start over? In other words, once we have posted the data, there does not seem to be a need for jscover to hold on to any data.

This will help stabilize our tests suites. I don't have a reproduction script here but I suspect you can run any test with jscover for a long time and observe this. If you have trouble with reproducing, I can try to put together my test case.

**Comment by tntim96** [comment]
Are you running in proxy mode or server mode? What kind of tests are you running so I can try to replicate?

**Comment by binodpanta** [comment]
Hi

I  using proxy mode as

-ws --proxy 

Etc

 I can send a sample test page tomorrow ( mine is qunit and dojo based based) although I think this could be reproducible with most any test page if you ran the same page on a loop a number of times.   I ran with chrome+ webdriver.


-Binod

**Comment by binodpanta** [comment]
Sorry for being sloppy about this but the page source of one of my test pages looks like this, if this helps with repro. It is not usable as provided of course, but at least hopefully gives an idea of what I am doing. My jscover is being hit with many tests like this and it runs out of memory after some time (even if I use -Xmx1025m -Xms1024m in the java invocation)


<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv='cache-control' content='no-cache'>
    <meta http-equiv='expires' content='0'>
    <meta http-equiv='pragma' content='no-cache'>

    <base href="../../../../"></base>



    <title>JavaScript unit tests</title>
    <link rel="stylesheet" type="text/css" href="../../../tools/javascript/libs/qunit/qunit.css">
    <link rel="stylesheet" type="text/css" href="../../../../ui/webwidgets/src/css/TextComponentDefaultVisualFamily.css">
</head>

<body>
    <div>
        <div id="qunit-fixture"></div>
        <div id="qunit"></div>
    </div>

    
    <script src="../../../../src/js/dojoConfigs/dojoConfig-test.js"></script>
    <script type="text/javascript" src="../../../../src/js/dojo/dojo/dojo.js"></script>

    
    <script type="text/javascript" src="../../../tools/javascript/libs/qunit/qunit.js"></script>

    <script type="text/javascript">
        QUnit.config.autostart = false;

        require(["Tests/unit_tests/plugins/tokenizer/TokenUnitTest"], function () {
            QUnit.start();
        });
</script>
</body>
</html>

**Comment by tntim96** [comment]
Why are you using the proxy if you're using QUnit? Why not use the JSCover server mode to serve this page?

**Comment by binodpanta** [comment]
Hi there

We use selenium to control the browser. We use proxy mode and point webdriver to use proxy then collect at end of test. Is using proxy not the most recommended approach?

**Comment by tntim96** [comment]
You should use server mode if you can, and if you're using QUnit, it should be possible.

**Comment by binodpanta** [comment]
Hmm I use jscover with selenium based tests. However For this case I use webdriver only to control the browser hence find it easy to use proxy mode. But also anotjer reason is that the server serving the files is often not in my control. Does it still make sense not to use proxy node then?



-Binod

**Comment by tntim96** [comment]
Proxy mode adds a lot of complications. If you are testing your JS while testing your application with Selenium, you'll have to use proxy mode or preferably pre-instrument with file-mode.

If you are just pointing at a HTML QUnit test, you can have the JSCover server serve that file, which is generally the easiest approach. I'm not sure if that's possible for your situation though.

**Comment by binodpanta** [comment]
I guess proxy is what I need then since I have to use the server developed internally for other reasons.

Are there any known issues with this mode? Is the memory leak somehow unique to proxy mode?

At this time I am trying to restart jscover after each test as a workaround.

Thanks

**Comment by tntim96** [comment]
Proxy mode adds a lot of overhead, and if there is a memory-leak, I don't have enough details to pin-point the problem. You can achieve code-coverage by first instrumenting in file-mode. Take a look at [this example](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system) of how to do it.

**Comment by binodpanta** [comment]
For me filesystem is hard to get right because I only offer the tooling and my users may have code that are in multiple locations I have no knowledge of. Their selenium based tests get coverage this way when coverage mode is on. Webserver mode issue is that users need to use a custom webserver. That is why I have found only proxy mode allowed my use case to work.

Thanks,
-Binod

**Comment by binodpanta** [comment]
We have come up with an interesting solution using mitm proxy and jscover which gets us ssl support too, we'll be glad to discuss/share if this can be useful

We also want to support source maps going forward esp with Babel ES6 and minifiication handling requirements, it might influence our tool choice somewhat. Are these two features in your priority list?

**Comment by tntim96** [comment]
>  mitm proxy and jscover which gets us ssl support too, we'll be glad to discuss/share if this can be useful

Sure. That would be great. Do you have a running example in github or elsewhere that's public?

> We also want to support source maps going forward esp with Babel ES6 and minifiication handling requirements, it might influence our tool choice somewhat. Are these two features in your priority list?

I've had this asked a few times, can see the benefit of it, and would like to add it in, but it would take a lot of time and effort. Branches and functions should instrument the same when minified, but the problem with line coverage is that it is instrumented per line, not per statement. As minification puts several, if not all, statements on one line, this would require a major architectural change. If you need it in the next several months, you'd probably have to look elsewhere.

I was looking at doing this in a new tool, [JSCover2|https://github.com/tntim96/JSCover2/], but that is still a work in progress.

**Comment by tntim96** [comment]
Actually, I've thought of another way this might work without a major change. Would the following approach be acceptable to you (if so I can probably start working on it straight away):
# Run JSCover with access to the source-map and original source (switch options to be added)
# When instrumenting, JSCover instruments the original source and inserts that, instead of trying to instrument the minified (and possibly obfuscated) code
# the rest of JSCover can then was as normal

I'd like to know how your set-up works with `mitm proxy` first, and whether this is all of use to you.

Also, what compressor do you use (e.g. Uglify 2) and do you include multiple files in one?

Let me know and I'll take a closer look and might be able to provide and time-estimate.

**Comment by tntim96** [comment]
Also, take a look at [--uri-to-file-matcher option](http://tntim96.github.io/JSCover/manual/manual.xml#proxyURIToFilePathTranslation). I assume your minified files contain the original source name with `-min` added. This option is only used for reporting, but a small modification could easily substitute in the original source for intrumentation instead of the minified version.
