### ISSUE TITLE
Syntax error bug in generated JavaScript

### ISSUE THREAD

**Issue by bitc** [tntim96/JSCover#208]
When trying to run JSCover on a large JavaScript file I get an error in the browser developer console:

```
Uncaught SyntaxError: Unexpected token -
```

Here is the relevant block of code that JSCover generated, note the offending line that tries to create a JavaScript function with the (invalid) name `visit8876_-1_1`

``` javascript
function visit8878_59_15(result) {
  _$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][15].ranCondition(result);
  return result;
}_$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][14].init(25, 21, '0 < (f = this.data[n] >> u)');
function visit8877_59_14(result) {
  _$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][14].ranCondition(result);
  return result;
}_$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['-1'][1].init(23, 36, 'visit8872_59_10(0 < (f = this.data[n] >> u)) && (k = !0 , l = m(f))');
function visit8876_-1_1(result) {
  _$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['-1'][1].ranCondition(result);
  return result;
}_$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][13].init(14, 8, 'u < this.A');
function visit8875_59_13(result) {
  _$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][13].ranCondition(result);
  return result;
}_$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][12].init(218, 46, 'visit8870_59_8(u < this.A) && visit8871_59_9(visit8872_59_10(0 < (f = this.data[n] >> u)) && (k = !0 , l = m(f)))');
function visit8874_59_12(result) {
  _$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][12].ranCondition(result);
  return result;
}_$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][11].init(204, 1, 'visit8869_59_7(visit8870_59_8(u < this.A) && visit8871_59_9(visit8872_59_10(0 < (f = this.data[n] >> u)) && (k = !0 , l = m(f))))');
function visit8873_59_11(result) {
  _$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][11].ranCondition(result);
  return result;
}_$jscoverage['/particles-ghcjs/_build/all.min.js'].branchData['59'][10].init(228, 21, '0 < (f = this.data[n] >> u)');
```

If you would like to see this error for yourself, here is a link to the HTML page containing the JavaScript that triggers this bug: https://bitc.github.io/tojs-benchmark/particles-ghcjs/index.min.html?barriers=l5&particles=500

**Comment by tntim96** [comment]
You can try the fix from source, [the latest drone.io build](https://drone.io/github.com/tntim96/JSCover/files)
 or the [maven snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/tntim96/JSCover/1.0.21-SNAPSHOT/). For maven you'll need to add sonatype repository with:
```xml
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

I can still see errors when instrumenting the compressed JS file, but they don't occur after formatting it with IntelliJ. You might want to try that before re-running to progress further. I think the errors occurring with the compressed source are due to Rhino, and might take some time to resolve.

If you could help isolate the problem with a smaller code example, that would help a lot.

**Comment by tntim96** [comment]
> I can still see errors when instrumenting the compressed JS file

These should be fixed now too.
