### ISSUE TITLE
Make js (-fs option) code instrumentation multithreaded

### ISSUE THREAD

**Issue by stasberkov** [tntim96/JSCover#209]
For big projects it takes noticeable time to instrument entire codebase. Run code instrumentation in several threads to complete it faster.

**Comment by tntim96** [comment]
I've uploaded a modified version of JSCover [here](http://jscover.sourceforge.net/JSCover-all.jar).

Are you able to try this and let me know the results? The default is 5 threads, but you can modify it with with something like `--threads=10`.

**Comment by stasberkov** [comment]
This is awesome! It works! Thanks man!

**Comment by tntim96** [comment]
Great. What thread count worked best for you? Just wondering if a default of 5 is too high.

**Comment by stasberkov** [comment]
I set to 8, this gives optimal results for my CPU: I have 4 core CPU with HT. This gives 8 threads (virtual cpu). Can you do this way: detect number of available logical threads and use this number, i.e. int threads = Runtime.getRuntime().availableProcessors(); ?
