### ISSUE TITLE
Russian words in text

### ISSUE THREAD

**Issue by xaircore** [tntim96/JSCover#213]
Hi. In my JavaScript file i have string with russian letters. Like this:
`
queryMethodName: 'Список',
`
Then i instrument this code, i have this string:
`
queryMethodName: '\u0421\u043f\u0438\u0441\u043e\u043a', 
`
Platform encoding: `windows-1251` 
How i can get this origin string represention in instrumented file?

**Comment by tntim96** [comment]
So is this solved? Maybe you can post the solution for others.
