### ISSUE TITLE
JSCover file system instrumentation

### ISSUE THREAD

**Issue by somnath10** [tntim96/JSCover#216]
Hi,
1.)I have been using JSCover file system instrumentation mode.
2.) I have successfully instrumented my .js files .
3.)ALso the instrumented .js files has been attached to the site.
4.)  Now  I am manually doing some tests in the instrumented files.
5.)So my last aim is to collect the coverage data generated.
6.)So for testing i am calling on the .js files jscoverage_serializeCoverageToJSON() method from a javascript file.
7)I am not using PhantomJS,or webdriver or selenium
8.)I am storing the outcome like
::
var str=jscoverage_serializeCoverageToJSON();
Then printing it like document.write(str);
I am not getting the coverage report.........Like how much lines got executed.......

If i am wrong then how to write it a javascript file to store the data coming from jscoverage_serializeCoverageToJSON();
also if i am writing in javascript then u cannot save it locally in a file....(i may hv to use node.js)

**Comment by tntim96** [comment]
Strange, that looks like it should work. `var str=jscoverage_serializeCoverageToJSON();` should return something like this generated from [the example in the documentation](https://github.com/tntim96/JSCover/tree/master/doc/example):
```
{"/script.js":{"lineData":[null,1,2,null,1,1,null,1,4,4,1,null,3,1,null,2,1,null,1,1,null,4,4,4,4,4],"functionData":[2,1,4],"branchData":{"9":[null,{"position":22,"nodeLength":23,"src":"element.id === 'radio1'","evalFalse":3,"evalTrue":1}],"12":[null,{"position":109,"nodeLength":23,"src":"element.id === 'radio2'","evalFalse":2,"evalTrue":1}],"15":[null,{"position":181,"nodeLength":23,"src":"element.id === 'radio3'","evalFalse":1,"evalTrue":1}],"18":[null,{"position":253,"nodeLength":23,"src":"element.id === 'radio4'","evalFalse":0,"evalTrue":1}]}}}
```

>  I am manually doing some tests in the instrumented files...if i am writing in javascript then u cannot save it locally in a file....(i may hv to use node.js)

If you are testing this manually the above approach should work. If you decide to use browser automation, the tool (e.g. PhantomJS, Selenium, HtmlUnit) should be able to write it out to the file-system.

**Comment by somnath10** [comment]
okk got u.... i am getting right now the output like u said....but my main aim is to get the report using file system mode..
After that what to do..Plzz guide....
I am using now PhantomJs....So right now getting the json....but the final coverage statistics i can't get...The one that is shown in firefox......

**Comment by somnath10** [comment]
Plzz throw some light....what to do after i get the output as 
{"/AppHeaderBar.js":{"lineData":[null,1,0,null,null,null,0,null,null,null,null,0,0,null,null,0,null,null,0,0,null,null,0,0,0],"functionData":[0,0,0],"branchData":{}}}
in PhantomJS..
I have to get coverage report...Right now i have got a json file saved into my file system....
Also i am using file system mode.....
Plzz give the steps what to do with the json file so that i can reach my goal using file system mode......How to get coverage report....What functions to use.......Give in details...
Right now i have written the code in PhantomJS




var page = require('webpage').create();
page.open('file:///C://Users/I323469/Desktop/JSCover/AppHeaderBar.js', function(status) 
{
           if (status == 'success') 
      
            {
 
         if (page.injectJs("C://Users/I323469/Desktop/JSCover/AppHeaderBar.js"))
{
 
           var json=  page.evaluate(function() 
            {
                return jscoverage_serializeCoverageToJSON() ;
              }
             );
}

}

  
                      var fs = require('fs');

                         var path = 'C:\Users\I323469\Desktop\JSCover\coverage.json';



       
             fs.write(path, json, 'w');
            phantom.exit();
              
           }
);

It is saving the output as you said...But my aim is in getting report
What should i do now

**Comment by tntim96** [comment]
> Right now i have got a json file saved into my file system...But my aim is in getting report

1. Save the coverage file as `jscoverage.json` in the same directory as your instrumented output that contains the other JSCover report files (e.g. `jscoverage.html`, `jscoverage.js`, etc...)
2. Append `jscoverage_isReport = true;` to the end of `jscoverage.js`
3. That should be all. You should now be able to open the report in `jscoverage.html`

**Comment by somnath10** [comment]
![som](https://cloud.githubusercontent.com/assets/15284181/10721316/d64ef178-7bc7-11e5-9155-e7c48df79b87.jpg)

**Comment by somnath10** [comment]
![som](https://cloud.githubusercontent.com/assets/15284181/10721319/eb451d28-7bc7-11e5-842e-9d353e4f158d.jpg)

**Comment by somnath10** [comment]
hi i did what t said..saved in the same directory in my file system where i had all the instrumented code(.js files)
Appended  jscoverage_isReport = true; to the end of jscoverage.js
Launched the jscoverage.html..but sorry to say the browser says 0 coverage
I checked the json file it is not empty.....
How to do plzzz say..

Also i have a question...After writing the command in cmd for file system mode for instrumenting i have all the instrumented files in the target folder in my dekstop....
Also i have these instrumented files in the url ....
But in the those files don't have jscoverage_serializeCoverageToJSON() function....It is only in the 
source directory which have these function
So after doing some manual testing in the url do that changes are reflected in the files saved in the local directory....
Bcz,the files in the url don't have these functions..They contain codes which are smaller in size than those which arelocally saved in the source directory

**Comment by tntim96** [comment]
> I checked the json file it is not empty.....

Can you put it somewhere for me to inspect?

**Comment by somnath10** [comment]
object		{1}
		
	/AppHeaderBar.js		{3}
		
	lineData		[25]
		
0	:	null
		
1	:	1
		
2	:	0
		
3	:	null
		
4	:	null
		
5	:	null
		
6	:	0
		
7	:	null
		
8	:	null
		
9	:	null
		
10	:	null
		
11	:	0
		
12	:	0
		
13	:	null
		
14	:	null
		
15	:	0
		
16	:	null
		
17	:	null
		
18	:	0
		
19	:	0
		
20	:	null
		
21	:	null
		
22	:	0
		
23	:	0
		
24	:	0
		
	functionData		[3]
		
0	:	0
		
1	:	0
		
2	:	0
		
	branchData		{0}

**Comment by tntim96** [comment]
That doesn't look valid JSON. Can you put the raw file somewhere or format the output better?

**Comment by somnath10** [comment]
it is showing these
Also i want to ask that i have many .js files in my system which are instrumented..i want the coverage report or my json should contain the description of all files..so whose jscoverage_serializeCoverageToJSON() to call..
I am not able to send that JSON file as yr dropbox doesn't support json files

**Comment by somnath10** [comment]
Plzz say what to do

**Comment by somnath10** [comment]
{"/AppHeaderBar.js":{"lineData":[null,1,0,null,null,null,0,null,null,null,null,0,0,null,null,0,null,null,0,0,null,null,0,0,0],"functionData":[0,0,0],"branchData":{}}

**Comment by somnath10** [comment]
the contents of the json files are these..Previously i sent u the text from an online json file viewer

**Comment by somnath10** [comment]
Ya i have copied it to my server

**Comment by tntim96** [comment]
The JSON is missing a closing `}` bracket.

**Comment by somnath10** [comment]
Plz answer me do the server containing the files after instrumentation contains the jscoverage_serializeCoverageToJSON() functions if i am using file mode..Or it is in the files locally contained in my directory..BCz the .js files in server don't hv that function

**Comment by tntim96** [comment]
> do the server containing the files after instrumentation contains the jscoverage_serializeCoverageToJSON() functions if i am using file mode

Yes.

**Comment by somnath10** [comment]
See after instrumenting say one file x.js of size 10kb gets reduced to 1kb......
Tell me do after instrumentation only we have that function

**Comment by somnath10** [comment]
?Also tha 1kb file doesn't have that function

**Comment by somnath10** [comment]
Also i have instrumented files in file system.How to replace it in server???

**Comment by tntim96** [comment]
> See after instrumenting say one file x.js of size 10kb gets reduced to 1kb

Can you look in `jscover.log` for errors?

**Comment by somnath10** [comment]
it is empty

**Comment by tntim96** [comment]
Can you see why it's smaller?

**Comment by tntim96** [comment]
> Also i have instrumented files in file system.How to replace it in server???

That depends on your build process. You can either copy it in manually or automate.

**Comment by somnath10** [comment]
So, plz say that originally .js files don't contain the jscoverage_serializeCoverageToJSON() function..only after appending it contains those functions

**Comment by somnath10** [comment]
?

**Comment by somnath10** [comment]
{"/App.js":{"lineData":[null,1,1,null,null,null,1,null,null,null,null,1,0,null,null,0,null,null,1,0,null,null,1,0,0],"functionData":[0,0,0],"branchData":{}}}
My JSON HAS THIS......IS THIS RIGHT JSON

**Comment by somnath10** [comment]
Also i don't want my browser to show my coverage reports ..I want the coverage reports to be saved in a file locally......

**Comment by somnath10** [comment]
Also say that right now i am testing an application which has a lot of js files..I have to instrument it...So after setup of the application i have saved it in the c directory..So i am trying to use the server mode to automate..So i am writting the code as in manual.....but in --directory-root=doc/example" in doc/example i will have to write the path in local system....also specifying the target a floder only gets created

**Comment by tntim96** [comment]
> originally .js files don't contain the jscoverage_serializeCoverageToJSON() function..only after appending it contains those functions

They get included as part of the instrumentation process. They are not appended as a separate step.

> My JSON HAS THIS......IS THIS RIGHT JSON

That looks correct.

> i don't want my browser to show my coverage reports ..I want the coverage reports to be saved in a file locally

The report data is in `jscoverage.json`. It can be converted to cobertura XML, LCOV, or you can view it with the JSCover HTML report files (e.g. `jscoverage.html` etc...)

> Also say that right now i am testing an application...

From this I assume you are testing against your application, not via a testing library such as Jasmine. In that case you can't use server mode. You have to use file-mode instrumentation and copy the files to your your server.

**Comment by patla** [comment]
Thnx ...So i have manually added my instrumented contents on my server...
Also running some manual testcases in my application like login page etc.So lot of coverage may be generated in the backdrop..I need to collect the report of .js files which are executed..Since i am new can u please suggest a way that how to collect the coverage from server manually if i writing script in phantomjs.. Right now i am thinking to open the page of my application using 
 page.open('xyz.com',function(status)
{
});
Then inside xyz.com there are many folders and inside them there are .js files..So trouble is that if it is my local system then i can parse the directory and call jscoverage_serializeCoverageToJSON() fumction but now in url , how to call those files.....Plzz give some hints ..better if u give some javascript code .

**Comment by patla** [comment]
In short how to call the same function of all the .js files inside a folder and subfolders available when we open
More tools---->Developer tools--->Then source
all files are inside it
Please say a way to do this by an example

**Comment by tntim96** [comment]
> I need to collect the report of .js files which are executed..Since i am new can u please suggest a way that how to collect the coverage from server manually if i writing script in phantomjs

```JavaScript
            var json = page.evaluate(function(){
                return jscoverage_serializeCoverageToJSON();
            });
            try {
                fs.write("target/phantom-jscover-qunit-fs/jscoverage.json", json, 'w');
            } catch(e) {
                console.log(e);
            }
```

> In short how to call the same function of all the .js files inside a folder and subfolders available when we open More tools---->Developer tools--->Then source

This will work automatically if the files have been instrumented.

**Comment by somnath10** [comment]
even if i run my test cases i am getting the same coverage for some .js files.Plzz ,say why it is  so?

**Comment by somnath10** [comment]
now in my application portal url  i replaced all the files in my application with the instrumented code by copying all those files and pasting it in the setup path in my directory.Then i launched my application and in  more tools--->developer tools-> i see my instrumented code ...
Now I run the tests....
Question1...
If i run these tests say login portal (change some password) all these generates some coverage report.So are these tests coverage are collected in the jscoverage_serializeCoverageTOJSON() function..Do i can get these coverage by calling login.js from my file directory....
i.e the path i should to point to file directory...???
Since the setup files of my application has been replaced with the instrumented code..So after doing some tests i can write code pointing to my directory in file system????

**Comment by somnath10** [comment]
So when i open my application and do some tests the coverage gets stored temporary or permanently...When i relaunch my application the previous coverage gets lost...How to access coverage from the file system.....after running my test cases.....do i need my script to file system to call those files function...

**Comment by somnath10** [comment]
// JavaScript Document
var page = require('webpage').create();
var dir = "C://Program Files (x86)/XYZ/";
var filepath='C:/Users/I323469/Desktop/phantom-jscover-qunit-fs/jscoverage.json';
var address;
var end=".js";
function endsWith(str, suffix)
{
return str.indexOf(suffix, str.length - suffix.length) !== -1;
}

page.open(http://localhost:6405/som/xyz.html, function(status) 
{
         if(status==='success')
         {
                console.log("Successfully entered the destined parent folder");
                 scanDirectory(dir);
                 }
                
               else
               console.log("Not reaching the requires webpage");
               
              
               
               
               
               phantom.exit();
               });
               
    
 
 var scanDirectory = function (dir) {
    var fs = require('fs');
    if (fs.exists(dir) && fs.isFile(dir)) {
                          
                   if(endsWith(dir, end))
                   {
                     
                                if(page.injectJs(dir))
                                {
                               var json=  page.evaluate(function() 
                        {
                          return jscoverage_serializeCoverageToJSON() ;
                        }
                       );
                       
                       
                       try {
                fs.write("filepath", json, 'w');
            } catch(e) {
                console.log(e);
            }
                       fs.write(filepath, json, 'w');
                                                     
                                
    } 
    }
    }
    else if (fs.isDirectory(dir)) {
        fs.list(dir).forEach(function (e) {
            if ( e !== "." && e !== ".." ) {    //< Avoid loops
                scanDirectory(dir + '/' + e);
            }
        });
    }
    }
          
scanDirectory(dir);


 I am getting the same coverage all the time...that html file is opening and inside that from more tools---> developers tools i can see all the instrumented files there....also where my application has set up files those are instrumented ...but i am getting same coverage....
I am trying to collect the coverage by calling  jscoverage_serializeCoverageTOJSON()  function of the files in my c:\ directory with an intuition that whatever manually i do some tests on my application all those are reflected in the file system directory .....Am i right..if right why same coverage after running some tests to..
if wrong suggest the solution of this scenario

**Comment by somnath10** [comment]
Need your suggestions!!!!

**Comment by tntim96** [comment]
Try putting the code I supplied in before your `phantom.exit();`.

Take a look at [this example](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system) which seems to match your scenario.

**Comment by somnath10** [comment]
Since my code is reading from my c:\ directory any tests which i run on my application is not recorded ...Is this so?

**Comment by tntim96** [comment]
Once you copy the instrumented files to your server, you no longer need to reference the original ones on the file-system. The function `jscoverage_serializeCoverageToJSON()` will be available to your browser whenever you load a page with the instrumented JavaScript.

**Comment by somnath10** [comment]
// JavaScript Document
var webPage = require('webpage');
var page = webPage.create();
var fs = require('fs');
page.open('http://localhost:6405/xyz/som.html/', function(status) {
  console.log('Status: ' + status);
  
  var json = page.evaluate(function(){
                return jscoverage_serializeCoverageToJSON();
            });
            try {
                fs.write("C:/Users/Desktop/phantom-jscover-qunit-fs/jscoverage.json", json, 'w');
            } catch(e) {
                console.log(e);
            }
  // Do other things here...
  phantom.exit();
});

I always get   cannot get variable jscoverage_serializeCoverageToJSON()....
Though when i open my application  in the console i write  jscoverage_serializeCoverageToJSON() function is available.......Why the error in phantomjs ???

**Comment by somnath10** [comment]
so what happens is that status is success but function is not called...but when i lauch my application in the console i type jscoverage_serializeCoverageToJSON()  is available....Again i write write eval("jscoverage_serializeCoverageToJSON()");  json is saved....but what's wrong with the above code

**Comment by somnath10** [comment]
?

**Comment by somnath10** [comment]
can u give the code to open the url(it is a html file) and the full code to access the function......?

**Comment by somnath10** [comment]
Please do say why the variable found eror is coming...I have checked in console in browser that jscoverage_serializeCoverageToJSON() is available

**Comment by tntim96** [comment]
This is more of a PhantomJS question, but anyway...you could try a `waitFor` condition as in [JSCover/src/test/javascript/lib/PhantomJS/run-jscover-qunit.js](https://github.com/tntim96/JSCover/blob/master/src/test/javascript/lib/PhantomJS/run-jscover-qunit.js).

**Comment by somnath10** [comment]
thanx..Got coverage reports without using waitFor function......
But if in firefox, in console i type eval("jscoverage_serializeCoverageToJSON()"); and press f12 and then save the json the coverage increases of some .js files when i run it.
But in programatic approach i run the tests and call my script using phantomJs the coverage is static
??Why??

**Comment by somnath10** [comment]
now according to you the page gets loaded the function jscoverage_serializeCoverageToJSON() is called for all instrumented files..But when i test the application manually the coverage should increase..Right now it is static
.......Please say ??

**Comment by tntim96** [comment]
If you call `jscoverage_serializeCoverageToJSON()` then do more testing, subsequent calls to `jscoverage_serializeCoverageToJSON()` will show increased coverage.

If you are moving from one page to the next, you can use `--local-storage` when instrumenting to save the coverage data to HTML5 local storage between pages.

**Comment by somnath10** [comment]
no no my aim is not calling that function from  firefox's console...My aim is that  my script in phantomjs when run from command prompt show increase in coverage.....Right now my script run's fine and shows some coverage..Now everytime i do run the script it generates the same report........?

**Comment by somnath10** [comment]
Do i should do more testing of the application.....but two different reports are generated...One which i write in firefox using eval("jscoverage_serializeCoverageToJSON()");  and then saving it,and other through the script

var webPage = require('webpage');
var page = webPage.create();
var filepath='C:/Users/abc/Desktop/tre/jscoverage.json';
page.open('http://localhost:8080/xyz.html', function(status) {
var fs = require('fs');
  var json = page.evaluate(function() {
    return jscoverage_serializeCoverageToJSON();
  });
     try {
                fs.write(filepath, json, 'w');
            } catch(e) {
                console.log(e);
            }

  //console.log(json);
  phantom.exit();

});

**Comment by somnath10** [comment]
after i run the tests,,,i open my cmd
type phantomjs filename  in my computer 
the file has the aforesaid command..
It generates a coverage but that is same

**Comment by somnath10** [comment]
Any solution sir???

**Comment by somnath10** [comment]
I am not moving from pages to pages....just in that page only adding members,deleting .......

**Comment by tntim96** [comment]
> Right now my script run's fine and shows some coverage..Now everytime i do run the script it generates the same report

If it's running the same test, of course it will generate the same report.

> Do i should do more testing of the application.....but two different reports are generated

I'm not sure what you mean. You should only need to run the test via PhantomJS. If you run multplie tests generating separate reports, they can be merged.

**Comment by somnath10** [comment]
So do you want me to run jscover+phantomjs+quint tests ....???
My approach:----
What i did is uploaded all .js files to server(instrumented ones)..then without using any automated testing scripts like qunit i manually tested my application......Then i run my script 

crack.js


var webPage = require('webpage');
var page = webPage.create();
var fs = require('fs');
page.open('http://localhost:6405/xyz/som.html/', function(status) {
  console.log('Status: ' + status);

  var json = page.evaluate(function(){
                return jscoverage_serializeCoverageToJSON();
            });
            try {
                fs.write("C:/Users/Desktop/phantom-jscover-qunit-fs/jscoverage.json", json, 'w');
            } catch(e) {
                console.log(e);
            }
  // Do other things here...
  phantom.exit();
});

Command i used in cmd is:

phantomjs crack.js

it is generating a json..when using my report everytime same coverage........Plzz Say what to do in this scenario

**Comment by tntim96** [comment]
> So do you want me to run jscover+phantomjs+quint tests ....???

No. From previous posts I gathered you were running tests against your server (which is why I linked to an example which does this).

> What i did is uploaded all .js files to server(instrumented ones)..then without using any automated testing scripts like qunit i manually tested my application......Then i run my script 

That looks correct.

> it is generating a json..when using my report everytime same coverage

Why do you expect the coverage to change if you run the test twice?

> Plzz Say what to do in this scenario

Well this test just opens the page and saves the coverage data. You need to run some JavaScript to get more coverage, for example click on something, or automate whatever you need to do to run your JavaScript in the PhantomJS browser (is this what `// Do other things here...` is? If so, save the coverage data after the `// Do other things here...`).

**Comment by somnath10** [comment]
Do you please give an idea about how to run the scripts automatically like if the page opens like login.html ,then how files say 
login.js ,loginView.js should automatically run in Background and increase the coverage.......I know it is a bit of PhantomJS concept but how...Actually even i call a button and write a script so that it gets clicked on  being loaded , then it increases a coverage by fraction....Do you know some shortcut way in this scenario which i should adopt so that coverage increases ...........

**Comment by tntim96** [comment]
Don't add a button to trigger the JavaScript, use the [PhantomJS API](http://phantomjs.org/api/) to simulate the user's actions.

**Comment by somnath10** [comment]
Yup ,I understand....This will work..
But I have a question...After I put all my instrumented code to server....I shut my application..Right now not using any tools phantomjs,selenium....
I relaunch my application again...Then in dev tools in firefox in console i see that jscoverage_serializeCoverageToJSON() is available...
Then ,I started running my tests on my application by clicking on buttons etc......
After that i want that this tests which i conducted manually gets stored in my file.....
u know if i write in browser's console eval("jscoverage_serializeCoverageToJSON()"); then it automatically gives the json data...
so without writing on browser's console is there any shortcut(like javascript code) that i run and gets the json stored of the currently run tests...
Because using phantomjs and running some scripts is kind of automating..I want users 
to instrument their code in server
Run tests manually without any scripts doing so..that is directly opening the application and do some clicks.....
And then take coverage.......

**Comment by somnath10** [comment]
plzz if possible give the code

**Comment by tntim96** [comment]
> so without writing on browser's console is there any shortcut(like javascript code) that i run and gets the json stored of the currently run tests...

No, but you could add a temporary button on your web-site to `POST` the data to your server, which would also need some temporary code to receive the data and either merge the results, or store them separately for later merging, or stream the data back directly to the user for them to save.

**Comment by patla** [comment]
So using jQuery like after loading the page then 
 $( document ).ready(function() {
 
        var json=eval("jscoverage_serializeCoverageToJSON()");
document.write(json); 

 });
writing something like that wouldn't it return some json...as in browser's console it returned json....
or using jquery and Ajax cannot we get json directory as AJAX has api to getJson...??

**Comment by tntim96** [comment]
I was thinking you should send the JSON to the server (or another server) to collect the results. For example:
```JavaScript
$.post( "/your-server-side-code", jscoverage_serializeCoverageToJSON());
```

You could even `POST` to another server running JSCover in server mode:
```JavaScript
$.post( "http://some.server.com/jscoverage-store", jscoverage_serializeCoverageToJSON());
```

**Comment by patla** [comment]
Can u plz explain i.e from the url using jQuery how i can call the jscoverage_serializeCoverageToJSON() function and save the json in my local system

**Comment by patla** [comment]
My aim is not to call jscoverage_serializeCoverageToJSON() function by using some headless browser's ..I need to collect the json stored in browser that is firefox,chrome......So any script that could probably collect the coverage from browser....Code ????

**Comment by patla** [comment]
Because i want my team not to use some headless browser or automate the process...I want after putting all the instrumenting scripts in my application...They should open my application and test it through existing browsers i.e by pressing buttons,..So after that some coverage is generated..To check we can see in browser's console by typing eval("jscoverage_serializeCoverageToJSON()"); ..It generates a json..
From here i want my team not to write this on browser's console and collect the json ....I want some scripts to run that call this jscoverage_serializeCoverageToJSON() function and json gets saved in my file system..then i can view using firefox or any....is there any way????if yes plz give some detailed steps how to do this?

**Comment by patla** [comment]
Because if we go on automating there will be thousands of test cases...So right whatever coverage is generated in browser's i need to collect that..the thing is that i want to invoke that function with some scripts and it should collect the json

**Comment by tntim96** [comment]
The example I gave does what you want. I even tried the second example locally. Please re-read it because I'm not sure how to explain it better.

I suggest you try the second method, i.e. run JSCover in sever mode and `POST` the data to it. It will automatically merge the results.

**Comment by patla** [comment]
but i don't have the json to send to server ...whether this code will allow me to retrieve the json which gets generated after i test all my application.....Actually it is showing nothing...and also where the file will get stored?
after instrumentation i started jscover in server mode....and run the command you gave...But nothing output i get??

**Comment by tntim96** [comment]
> but i don't have the json to send to server...it is showing nothing

You said you got this working in your second comment. Also make sure you instrument with `--local-storage` as suggested above.

> where the file will get stored?

That's for you to determine - see last comment below.

> after instrumentation i started jscover in server mode....and run the command you gave...But nothing output i get

I don't know your set-up so can't help much. Maybe you should try the first method with:
```Javascript
$.post( "/your-server-side-code", jscoverage_serializeCoverageToJSON());
```

This means you have to write some server side code to save the data somewhere. You can use the JSCover API or command line to merge the received JSON.

**Comment by patla** [comment]
is this possible using java using java rich api..i.e open the url ,and then fetch some information..

**Comment by tntim96** [comment]
I'm not sure what you mean.

**Comment by patla** [comment]
that is by using java language cannot we collect the json that is returned by jscoverage_serializeToJSON() function...

**Comment by tntim96** [comment]
If you were using an WebDriver you could. As your not, you'll have to `POST` the data to a server (Java or other) to get the JSON as explained above.

**Comment by patla** [comment]
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;


public class Demo {
	
	public static void main(String[] args) {
		  WebDriver driver = new FirefoxDriver();
		  driver.get("http://localhost:6405/xyz/Login.html");
		  
		  String i = driver.getCurrentUrl();
		  System.out.println(i);
		  JavascriptExecutor webClient ='-----------' ;
		String json = (String)((JavascriptExecutor) webClient).executeScript("return jscoverage_serializeCoverageToJSON();");
		System.out.println(json);  
		driver.close();
		  
		 }
}
i was tryinh webdriver....what to initialize webdriver with to run this code.......so that i can see the json in my console..please help....actually experimenting with webdriver......

**Comment by patla** [comment]
in place of  JavascriptExecutor webClient ='-----------' ;what to initialize wit...facing trouble

**Comment by tntim96** [comment]
I don't think you need the `JavascriptExecutor webClient ='-----------' ;` line. 

Change
```Java
String json = (String)((JavascriptExecutor) webClient).executeScript("return jscoverage_serializeCoverageToJSON();");
```
to
```Java
String json = (String)((JavascriptExecutor) driver).executeScript("return jscoverage_serializeCoverageToJSON();");
```

**Comment by patla** [comment]
thanx for helping me using  the webdriver.(Selenium)...
But sorry to say using post method i couldn't  iimplement as i failed....Can you give me a full fledged example of how to programatically open a url(my appliaction in server) ,call that function and store it somewhere....(using post).....

**Comment by tntim96** [comment]
> how to programatically open a url(my appliaction in server)

Opening a URL is done client side. The JavaScript for that is provided above.

> call that function and store it somewhere....(using post)

There is nothing special about the `POST`. Just save it to a file and use JSCover to merge the files later.
