### ISSUE TITLE
coverage data can not be reflected to the JSON file

### ISSUE THREAD

**Issue by zhou777** [tntim96/JSCover#217]
1)a part of  instrumented code:
...
  _$jscoverage['/*/*/*.js'].lineData[54]++;
alert(_$jscoverage['/*/*/*.js'].lineData[54]);
  data.getIndexHTML();
  _$jscoverage['/*/*/*.js'].lineData[55]++;
  cookie.setCookie("isLogin", "false");
...
2)json data
"lineData":...,0,0...

 when I run  the test case by chrome,(alert(_$jscoverage['/*/*/*.js'].lineData[54]);) was executed,
And the result is 1.
why can not be reflected to the JSON file?

※Only a part of the code in a file will have this problem.

**Comment by tntim96** [comment]
Are you saving the JSON before it is executed? Can you provide a code snippet for me to reproduce the issue?

**Comment by zhou777** [comment]
>>Are you saving the JSON before it is executed?
when the testCase is finished,then  I save the JSON file(self.report()).

>>Can you provide a code snippet for me to reproduce the issue?
sorry,Because it involves ISMS,  I can't provide JS code.
At before, is there a similar problem?

code snippet of  testCase :
   (testCase by selenium2 + python)
    def test_login_logout_push(self):
#      login push        
        driver = self.driver
        driver.get(self.base_url + "/")
        time.sleep(2)
        driver.find_element_by_id("login").click()
        element = driver.find_element_by_id("loginButton").is_displayed()
        self.assertTrue(element)
#     password input
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("admin")
        driver.find_element_by_id("loginButton").click()
        time.sleep(2)
#       logout put
        driver.find_element_by_id("login").click()
        time.sleep(2)

        self.report()
        driver.close()

    def report(self):
        # json data create
        coverageJSON = self.driver.execute_script("return jscoverage_serializeCoverageToJSON();")  
        file = open("C:/src/jscoverage.json","w")
            
        file.write(coverageJSON)
        file.close()

**Comment by tntim96** [comment]
No, I haven't seen this before. I suspect it's a timing issue, or the code is executed in another context. Have you tried with `--local-storage`?

**Comment by zhou777** [comment]
I only used cookie,did not used html5's local storage.

**Comment by tntim96** [comment]
Can you trying the file instrumentation with `--local-storage` and see if the result is the same?
