### ISSUE TITLE
Coverage via proxy on PhantomJS (Selenium automation).

### ISSUE THREAD

**Issue by jwaliszko** [tntim96/JSCover#220]
I'd like to collect code coverage statistics during few coded UI tests execution. 

I'm working with JSCover 1.0.23-SNAPSHOT, XUnit 2.1.0,  Selenium.WebDriver 2.48.2, PhantomJS 2.0.0 and basic ASP.NET MVC 4 application hosted in IISExpress 10 on Win7 machine.

* When using JSCover through proxy on Firefox, everything works as expected:

 Start JSCover with proxy args:
 ```
>java -jar JSCover-all.jar -ws --proxy --port=3128 --report-dir=reports --local-storage
```

 Setup WebDriver in C#:
 ```
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;

var proxy = new Proxy {HttpProxy = "localhost:3128"};
var capabilities = new DesiredCapabilities();
capabilities.SetCapability(CapabilityType.Proxy, proxy);
Driver = new FirefoxDriver(capabilities);
```

 Invoke few tests:
 ```
Driver.Navigate().GoToUrl("http://localhost:51622/"); // site hosted on IISExpress
Driver.FindElementByXPath(...).Click(); // etc.
```

 Expect results to be generated (awesome!):

 ![image](https://cloud.githubusercontent.com/assets/1596462/12054633/647d3f00-af25-11e5-8b55-3d88836e9adc.png)

* When using JSCover through proxy on PhantomJS instead, unfortunately either it doesn't work, or I'm doing something incorrectly:

 Start JSCover with proxy args (same as before):
 ```
>java -jar JSCover-all.jar -ws --proxy --port=3128 --report-dir=reports --local-storage
```

 Start PhantomJS:
 ```
>phantomjs --proxy=localhost:3128 --proxy-type=http --webdriver=4444
```

 Setup WebDriver in C#:
 ```
using OpenQA.Selenium;
using OpenQA.Selenium.PhantomJS;
using OpenQA.Selenium.Remote;

var proxy = new Proxy {HttpProxy = "localhost:3128"};
var capabilities = DesiredCapabilities.PhantomJS();
capabilities.SetCapability(CapabilityType.Proxy, proxy);            
Driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), capabilities);
```

 Invoke few tests (same as before):
 ```
Driver.Navigate().GoToUrl("http://localhost:51622/"); // site hosted on IISExpress
Driver.FindElementByXPath(...).Click(); // etc.
```

 Expect unavailable results (checking in Firefox browser, by pasting expected results URL manually):

 ![image 1](https://cloud.githubusercontent.com/assets/1596462/12054702/dc6276f2-af25-11e5-829f-526e8b08112b.png)

 Supplementary logs:

 ![image](https://cloud.githubusercontent.com/assets/1596462/12057611/181f6890-af43-11e5-8de4-e97222a7849e.png)

 ![image](https://cloud.githubusercontent.com/assets/1596462/12058042/e061cf24-af47-11e5-9493-e87a4b65dd16.png)

Is it possible to configure coverage that or similar way?

I'm interested in proxy version in particular, I haven't tried explicit instrumentation.
Also I'm not sure if this is a problem related to JSCover, or maybe some other component used here.

Regards

**Comment by tntim96** [comment]
JSCover can collect coverage when run as a proxy, but it is preferable to instrument the JavaScript first and not use the proxy mode unless pre-instrumenting is not possible.

This approach should work fine (I've used PhantomJS too via [Ghostdriver](https://github.com/detro/ghostdriver))

I'm guessing in your second version of FireFox, the 404 is occurring because you haven't manually configured the proxy in the browser.

Can you just replace `new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), capabilities);` with `new PhantomJSDriver()` as done [here](http://www.andykelk.net/tech/headless-browser-testing-with-phantomjs-selenium-webdriver-c-nunit-and-mono)?

**Comment by jwaliszko** [comment]
Indeed I've missed the manual proxy configuration for Firefox. 
After appropriate setup, I'm able to retrieve the report page, but without any coverage statistics:

![image](https://cloud.githubusercontent.com/assets/1596462/12080176/f4d7da1c-b252-11e5-8669-66edae5908a9.png)

I've tried also alternative C# configurations, e.g.
```
var service = PhantomJSDriverService.CreateDefaultService();
service.AddArgument("--proxy=localhost:3128");
Driver = new PhantomJSDriver(service);
```

or
```
var options = new PhantomJSOptions();
options.AddAdditionalCapability(CapabilityType.Proxy, new Dictionary<string, string>
{
    {"proxyType", "MANUAL"},
    {"httpProxy", "localhost:3128"},
});            

var service = PhantomJSDriverService.CreateDefaultService();
service.ProxyType = "http";
service.Proxy = "localhost:3128";
service.IgnoreSslErrors = true;
service.WebSecurity = false;

Driver = new PhantomJSDriver(service, options, TimeSpan.FromSeconds(10.0));
Driver.Manage().Timeouts().ImplicitlyWait(new TimeSpan(0, 0, 10));
```

Still no results. 

To avoid confusion with Firefox verifications, what I've alternatively tried is to navigate to the results page using the driver itself:
```
Driver.Navigate().GoToUrl("http://localhost:51622/jscoverage.html");
```
but got 404:

![image](https://cloud.githubusercontent.com/assets/1596462/12080107/f38bac4e-b250-11e5-8e97-7dc36d3505bb.png)

![image](https://cloud.githubusercontent.com/assets/1596462/12080173/ed951dc8-b252-11e5-95c5-2a2de8d79252.png)

**Comment by tntim96** [comment]
It looks like a PhantomJS proxy issue - that last test you did seems to confirm it.

**Comment by jwaliszko** [comment]
Thanks for your time.
Maybe someone from PhantomJS (@ariya, @Vitallium) would like to take a look at this issue.
