### ISSUE TITLE
any plans to migrate to the Nashorn parser?

### ISSUE THREAD

**Issue by grokwich** [tntim96/JSCover#221]
http://openjdk.java.net/jeps/236

**Comment by tntim96** [comment]
I'll try it in https://github.com/tntim96/JSCover2/ (unless you want to beat me to it with a PR) which is a WIP. If it works OK I'll swap to it.

**Comment by grokwich** [comment]
Cool.  If i could only find the time i would love to work on a PR.  But your Closure work sounds like another good alternative.  I did not realize Closure was not using Rhino.  Thank you for your great work and the quick response.

**Comment by tntim96** [comment]
I got the latest EA JDK8 and latest JDK 9 parser but didn't find `jdk.nashorn.api.tree` exposed API package. Do you know which download has this available, or does it have to be built from source?

**Comment by grokwich** [comment]
Sorry, not sure about that?

I believe the jdk.nashorn.api.* packages were first introduced in JDK9 (not
part of JDK8).

I would think it should be part of the current JDK9 download?
