### ISSUE TITLE
Add asynchronous option to jscoverage_report()

### ISSUE THREAD

**Issue by elvis-epx** [tntim96/JSCover#227]
In some platforms (e.g. Raspberry) the jscoverage_report() takes so much time that it timeouts. Since a synchronous request cannot have its timeout configured, the option is to add an asynchonous option with a callback. Attached is a suggested patch that implements this feature, I have tested it in my test environment with success.

[jscoverdiff.zip](https://github.com/tntim96/JSCover/files/222342/jscoverdiff.zip)

**Comment by tntim96** [comment]
Looks good, just double checking the code before committing.

**Comment by tntim96** [comment]
Are you happy with the patch as is, or were you wanting for it to be wired into the UI?

**Comment by elvis-epx** [comment]
I'm not sure I follow, but I am happy with it, because it solves my problem. Perhaps the timeout should be longer, or configurable, but 120s is enough in Raspberry 3, which is not the typical machine.

**Comment by tntim96** [comment]
The fix has been committed. You can get the latest build from https://drone.io/github.com/tntim96/JSCover/files.

**Comment by tntim96** [comment]
Just a note, I'm going to remove the deprecated synchronous call in #232.

I'm also going to change the call-back arguments to just call the request object when `request.readyState == 4`. Let me know if you see any potential issues with this.

**Comment by elvis-epx** [comment]
No problem from my side.

--
Elvis
