### ISSUE TITLE
I am unable to how to start with jscover.

### ISSUE THREAD

**Issue by poojagangurde** [tntim96/JSCover#228]
i want to check client side coverage of our application. Our application has js files. i have created html files referring to those js files. What is the next step to do? How do I integrate my scripts with Jscover? I am running those scripts on Selenium using Testng and ant.

**Comment by tntim96** [comment]
There are some Selenium examples in https://github.com/tntim96/JSCover-samples. Take a look at [WebDriverJasmineTestBase](https://github.com/tntim96/JSCover-samples/blob/master/src/main/java/jscover/webdriver/jasmine/WebDriverJasmineTestBase.java). The preferred way of running would be the `shouldRunJasmineTestAndStoreResultViaJavaScriptCall` test.
