### ISSUE TITLE
jscoverage.html not found

### ISSUE THREAD

**Issue by mendrinos** [tntim96/JSCover#229]
When I am running the web server from:

JSCover-1.0.24/examples/localStorage-proxy/web-server.sh

I expect to be able to run the selenium-ide-proxy.html from the Selenium IDE.

but this is what I get:
<img width="770" alt="screen shot 2016-04-28 at 8 36 50 pm" src="https://cloud.githubusercontent.com/assets/1592441/14885980/f8d20f00-0d80-11e6-8e3b-54d982ca5b2e.png">

Any idea?

**Comment by tntim96** [comment]
For that example, see the [Readme.md](https://github.com/tntim96/JSCover/blob/master/examples/localStorage-proxy/Readme.md). You also have to start the proxy server, edit your hosts file and configure your browser to use the proxy.
