### ISSUE TITLE
Add expected DocumentType & DTD to cobertura formatted xml

### ISSUE THREAD

**Issue by BearPuncher** [tntim96/JSCover#231]
Hi,

The generated cobertura XML coverage report is missing the DOCTYPE & DTD declaration that Cobertura, and other Cobertura formatters, append. Could you please append the DocumentType & DTD declaration for conformity?

The expected DocumentType string for Cobertura XML is;
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">

You can see it being printed here in the Cobertura XML reporting code;
https://github.com/christ66/cobertura/blob/master/cobertura/src/main/java/net/sourceforge/cobertura/reporting/xml/XMLReport.java#L63

Cheers,
Daniel

**Comment by tntim96** [comment]
I just checked by running `src/test-integration/java/jscover/report/coberturaxml/CoberturaXmlGeneratorIntegrationTest.shouldGenerateXml`, and it appears to be there.

I also double checked by running `java -cp target/dist/JSCover-all.jar jscover.report.Main --format=COBERTURAXML target/example-report-yui3/ doc/example-report-yui3/original-src/` and it starts with:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
```

Can you double check?

**Comment by BearPuncher** [comment]
Thanks for the quick response; I'll double check, realized I'm mostly likely consuming an old version as well. I'll close this for now.
