### ISSUE TITLE
How to embed in a TestNG @BeforeSuite method

### ISSUE THREAD

**Issue by ph-hs** [tntim96/JSCover#233]
I'm orchestrating the starting of an embedded Jetty in a @BeforeSuite method (TestNG).  The same test invocation is coordinating a WebDriver instance for automated clicking of the web application being tested.

I'm like to be able to similarly instantiate the JSCover proxy in the @BeforeSuite method, and in an @AfterSuite method collect the coverage result, and spit out XML/txt for later reporting.

How to do that?

Is jscover.Main the class I need to be inspired by - the whole lifecycle apparent in there?

**Comment by tntim96** [comment]
Take a look at the samples at https://github.com/tntim96/JSCover-samples. The JUnit examples should be easily converted to TestNG.

**Comment by ph-hs** [comment]
Thanks - that helped
