### ISSUE TITLE
Poor performance when used together with systemjs 0.19.37

### ISSUE THREAD

**Issue by stasberkov** [tntim96/JSCover#235]
We discovered significant performance slowdown of tests when we upgraded codebase to systemjs 0.19.37 (from 0.19.17). We started investigation and realized that before unload handler from
```
if (typeof(jscoverbeforeunload) === "undefined") {
    var jscoverbeforeunload = (window.onbeforeunload) ? window.onbeforeunload : function () {};
    window.onbeforeunload = function () {
        jscoverbeforeunload();
        if ((typeof(_$jscoverage) !== "undefined") && (typeof(Storage) !== "undefined"))
            localStorage["jscover"] = jscoverage_serializeCoverageToJSON();
    };
}
```
started being executed for each file (not single time as it was before). This started happening since systemjs started wrapping all loaded code into anonymous function:
```
(function(System, SystemJS) {function BranchData() {
...
if (typeof(jscoverbeforeunload) === "undefined") {
    var jscoverbeforeunload = (window.onbeforeunload) ? window.onbeforeunload : function () {};
    window.onbeforeunload = function () {
        jscoverbeforeunload();
        if ((typeof(_$jscoverage) !== "undefined") && (typeof(Storage) !== "undefined"))
            localStorage["jscover"] = jscoverage_serializeCoverageToJSON();
    };
}
...
})(System, System);
```
As a result `jscoverbeforeunload` variable became local. `if (typeof(jscoverbeforeunload) === "undefined") {` check is evaluated each time as "true".

Please fix how global variables are defined. Your coverage tool is really awesome.

**Comment by tntim96** [comment]
Just had a quick read...so {{jscoverbeforeunload}} should be {{window.jscoverbeforeunload}}?

**Comment by tntim96** [comment]
The fix described above is available at https://drone.io/github.com/tntim96/JSCover/files and also in the maven snapshot:
```
<dependency>
    <groupId>com.github.tntim96</groupId>
    <artifactId>JSCover</artifactId>
    <version>1.0.25-SNAPSHOT</version>
</dependency>
...
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

Let me know if it works for you OK. One extra thing to note, is the [JavaScript save is now asynchornous](https://github.com/tntim96/JSCover/issues/232) in this snapshot.

**Comment by stasberkov** [comment]
Cool! Thanks! Will try!

**Comment by stasberkov** [comment]
It works great! Thank you for quick fix!
