### ISSUE TITLE
run-jscover-jasmine2.js exits with timeout

### ISSUE THREAD

**Issue by zhekaus** [tntim96/JSCover#239]
I’m trying to get a cover report with phantomjs.
Whatever I try I’ve got 'waitFor()' timeout.
I work on Windows 10
I’ve got a very simple test of a very simple code.
In the Chrome everything works fine.

PS. jasmine 2.4.1 and 2.5.2
JSCover-1.0.24
phantomjs-2.1.1-windows

**Comment by tntim96** [comment]
> I’ve got a very simple test of a very simple code.

Can you put a simple example reproducing the problem in Github for me to investigate further? Also, does your sample work with https://github.com/ariya/phantomjs/blob/master/examples/run-jasmine2.js? If not, and I can find the issue, I'll fix in the original source (as done [here](https://github.com/ariya/phantomjs/issues/14280)) and incorporate the fix (as done [here](https://github.com/tntim96/JSCover/commit/99133824f4f263d2f101bd591ceea79d87127796)).

**Comment by tntim96** [comment]
Any update? Do the examples in https://github.com/tntim96/JSCover/tree/master/examples work for you?
How about [phantomJS-file-system](https://github.com/tntim96/JSCover/tree/master/examples/phantomJS-file-system).
