### ISSUE TITLE
Using JSCOVER

### ISSUE THREAD

**Issue by satishNeelakanta** [tntim96/JSCover#240]
Hi,

I'm very new to JSCover, Requirement given to me is we have to do JS codecoverage for our application, In Our application HTML pages are created on fly, Please help me how can I continue further

**Comment by tntim96** [comment]
If you can run a test, you should be able to collect code-coverage metrics.

What you can do is look at the examples to see if they may work for you.

There are [some examples in the JSCover project](https://github.com/tntim96/JSCover/tree/master/examples).

[JSCover Samples](https://github.com/tntim96/JSCover-samples) also have some examples you can look at.
