### ISSUE TITLE
JSCover fails to merge / save coverage data to the json and xml files

### ISSUE THREAD

**Issue by cobexer** [tntim96/JSCover#242]
Since switching from the JSCover-all.jar to the jcenter jscover Gradle "com.github.tntim96:JSCover:1.0.23" dependency JSCover no longer produces correct coverage data.

The jscoverage.json file has around 95k json and around 60k 0 bytes (Hex: 0x00).

I also tried version 1.0.24 and 1.0.25 with the same results.

I start JSCover using ant with:
```xml
  <property name="jscover.main.jar" location="com.github.tntim96-JSCover.jar"/>

  <path id="jscover.classpath">
    <pathelement location="org.mozilla-rhino.jar"/>
    <pathelement location="${jscover.main.jar}"/>
  </path>

  <target name="jscover-start">
    <java classname="jscover.Main" classpathref="jscover.classpath" fork="true" spawn="true">
    ...
```
The log file doesn't contain anything more useful than the message I get during shutdown:
```
[java] Exception in thread "main" java.lang.RuntimeException: org.mozilla.javascript.json.JsonParser$ParseException: Unexpected token: 
[java] 	at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:436)
[java] 	at jscover.report.Main.saveCoberturaXml(Main.java:465)
[java] 	at jscover.report.Main.runReport(Main.java:409)
[java] 	at jscover.report.Main.runMain(Main.java:394)
[java] 	at jscover.report.Main.main(Main.java:366)
[java] Caused by: org.mozilla.javascript.json.JsonParser$ParseException: Unexpected token: 
[java] 	at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:82)
[java] 	at org.mozilla.javascript.json.JsonParser.readArray(JsonParser.java:167)
[java] 	at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:60)
[java] 	at org.mozilla.javascript.json.JsonParser.readObject(JsonParser.java:119)
[java] 	at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:58)
[java] 	at org.mozilla.javascript.json.JsonParser.readObject(JsonParser.java:119)
[java] 	at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:58)
[java] 	at org.mozilla.javascript.json.JsonParser.parseValue(JsonParser.java:44)
[java] 	at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:412)
[java] 	... 4 more
```

From jscover.log
```
20161221 17:21:22.604,912,INFO,"Saving/merging JSON with existing JSON",jscover.report.JSONDataSaver,
20161221 17:21:22.604,912,INFO,"Saving/merging JSON with existing JSON",jscover.report.JSONDataSaver,
20161221 17:21:22.607,912,SEVERE,"Error saving coverage data",jscover.server.InstrumentingRequestHandler,
java.lang.RuntimeException: org.mozilla.javascript.json.JsonParser$ParseException: Unexpected token: n
        at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:436)
        at jscover.report.JSONDataMerger.mergeJSONCoverageStrings(JSONDataMerger.java:368)
        at jscover.report.JSONDataSaver.saveJSONData(JSONDataSaver.java:373)
        at jscover.server.InstrumentingRequestHandler.storeReport(InstrumentingRequestHandler.java:421)
        at jscover.server.InstrumentingRequestHandler.handlePostOrPut(InstrumentingRequestHandler.java:391)
        at jscover.server.HttpServer.run(HttpServer.java:418)
Caused by: org.mozilla.javascript.json.JsonParser$ParseException: Unexpected token: n
        at org.mozilla.javascript.json.JsonParser.readNull(JsonParser.java:367)
        at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:68)
        at org.mozilla.javascript.json.JsonParser.readArray(JsonParser.java:167)
        at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:60)
        at org.mozilla.javascript.json.JsonParser.readObject(JsonParser.java:119)
        at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:58)
        at org.mozilla.javascript.json.JsonParser.readObject(JsonParser.java:119)
        at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:58)
        at org.mozilla.javascript.json.JsonParser.parseValue(JsonParser.java:44)
        at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:412)
        ... 5 more

20161221 17:21:22.607,912,FINE,"Sending response status:200 OK mime:text/plain",jscover.server.HttpServer,
```

Any Ideas?

**Comment by tntim96** [comment]
This looks like a dependency problem. JSCover depends on Rhino, like plenty of other projects. I'm guessing you have another library which uses a different version of Rhino, and that that's the one on the classpath.

JSCover 1.0.24/5 use Rhino 1.7.7.1.
JScover 1.0.23 uses 1.7.7

https://docs.gradle.org/current/userguide/userguide_single.html#sec:listing_dependencies

**Comment by cobexer** [comment]
# ./gradlew dependencies
\--- com.github.tntim96:JSCover:1.0.25
     \--- org.mozilla:rhino:1.7.7.1
I also checked the export folder of my build and on the build server and the jar is version 1.7.7.1

**Comment by tntim96** [comment]
Next thing is to inspect the JARs from your repository. They may have not downloaded correctly, or they may be stored incorrectly on an internal repository if you use one.

This is what I get locally:
```openssl sha1 ~/.m2/repository/com/github/tntim96/JSCover/1.0.25/JSCover-1.0.25.jar
SHA1(/home/tim/.m2/repository/com/github/tntim96/JSCover/1.0.25/JSCover-1.0.25.jar)= 72363995f65015370a6705240d6daa913dd8c18b
cat ~/.m2/repository/com/github/tntim96/JSCover/1.0.25/JSCover-1.0.25.jar.sha1 
72363995f65015370a6705240d6daa913dd8c18b```

```openssl sha1 ~/.m2/repository/org/mozilla/rhino/1.7.7.1/rhino-1.7.7.1.jar
SHA1(/home/tim/.m2/repository/org/mozilla/rhino/1.7.7.1/rhino-1.7.7.1.jar)= 2e8f8ebc42e5df8bcef5c78dd44387176c9aa98e
cat ~/.m2/repository/org/mozilla/rhino/1.7.7.1/rhino-1.7.7.1.jar.sha1 
2e8f8ebc42e5df8bcef5c78dd44387176c9aa98e
```

**Comment by cobexer** [comment]
both jars match:
```
$ sha1sum.exe dependencies/*.jar
72363995f65015370a6705240d6daa913dd8c18b *dependencies/com.github.tntim96-JSCover.jar
2e8f8ebc42e5df8bcef5c78dd44387176c9aa98e *dependencies/org.mozilla-rhino.jar
```
Also running JSCover with --log=FINEST did not add any more useful information to the logs, is there an option to enable even more debug information?

At some point during the tests the jscoverage.json file has a bunch of 0x00 bytes in it (like 100k of them) and then merging fails and the coverage file is corrupt.

The exact error message appears to vary based on where the null bytes start.

**Comment by tntim96** [comment]
> Since switching from the JSCover-all.jar to the jcenter jscover Gradle "com.github.tntim96:JSCover:1.0.23" dependency JSCover no longer produces correct coverage data.

If the JARs are the same then I'm not sure what could be different. So JSCover-all.jar for version 1.0.25 works with nothing else changed?

> The jscoverage.json file has around 95k json and around 60k 0 bytes

I've seen this before when the user extracted the JSON into web-driver and failed to close the stream when writing, but it looks like you're using the JSCover server to save. Is your client submitting all the data before exiting?

> is there an option to enable even more debug information

I've uploaded a snapshot (version JSCover-1.0.26-20161223.003501-3) with more logging which might help. With finest logging it should log the data to be saved, and any data to be merged before attempting the save/merge.

```
<dependency>
    <groupId>com.github.tntim96</groupId>
    <artifactId>JSCover</artifactId>
    <version>1.0.26-SNAPSHOT</version>
</dependency>
```

```
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by cobexer** [comment]
Sorry for not responding for so long, I have been on vacation and still haven't found the time to test this again. I hope I'll find some time next week to test this!

**Comment by cobexer** [comment]
> So JSCover-all.jar for version 1.0.25 works with nothing else changed?

The last -all tested was 1.0.23 (which is why I compared it to that above - this also reduces my known differences to just the way the JVM is started)

> I've seen this before when the user extracted the JSON into web-driver and failed to close the stream when writing, but it looks like you're using the JSCover server to save.

Which is why I opened this issue already back in december before going on vacation >.>
I start jscover.Main with only org.mozilla-rhino and jscover on the classpach passing -ws behind an Apache reverse proxy.

> Is your client submitting all the data before exiting?

The log below is the first request to /jscoverage-store where the first 3 loggings of JSON data have valid data (tested in Chrome) and then the data is corrupt after exactly 80k
```
20170117 5:02:09.010,160,FINE,"Request: POST //jscoverage-store HTTP/1.1",jscover.server.HttpServer,
20170117 5:02:09.010,160,FINEST,"Header: Host: localhost:8008",jscover.server.HttpServer,
20170117 5:02:09.010,160,FINEST,"Header: Accept: */*",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: Content-Type: application/json",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: Referer: http://host/app/",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: Accept-Language: de-AT",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: Accept-Encoding: gzip, deflate",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: Cache-Control: no-cache",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: X-Forwarded-For: 2001:fake:61a5, 2001:fake:9351",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: X-Forwarded-Host: host, host",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: X-Forwarded-Server: host.example.com, host.example.com",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: Connection: Keep-Alive",jscover.server.HttpServer,
20170117 5:02:09.011,160,FINEST,"Header: Content-Length: 149882",jscover.server.HttpServer,
20170117 5:02:09.012,160,FINE,"Storing report",jscover.server.InstrumentingRequestHandler,
20170117 5:02:09.308,160,FINEST,"149882 bytes valid JSON",jscover.server.InstrumentingRequestHandler,
20170117 5:02:09.309,160,FINEST,"Saving/merging JSON data",jscover.report.JSONDataSaver,
20170117 5:02:09.309,160,FINEST,"Saving/merging JSON data",jscover.report.JSONDataSaver,
20170117 5:02:09.309,160,FINEST,"149882 bytes valid JSON",jscover.report.JSONDataSaver,
20170117 5:02:09.309,160,FINEST,"149882 bytes valid JSON",jscover.report.JSONDataSaver,
20170117 5:02:09.313,160,INFO,"Saving/merging JSON with existing JSON",jscover.report.JSONDataSaver,
20170117 5:02:09.313,160,INFO,"Saving/merging JSON with existing JSON",jscover.report.JSONDataSaver,
20170117 5:02:09.313,160,FINEST,"81920 bytes valid JSON and 68913 bytes 0x00",jscover.report.JSONDataSaver,
20170117 5:02:09.313,160,FINEST,"81920 bytes valid looking JSON and 68913 bytes 0x00",jscover.report.JSONDataSaver,
20170117 5:02:09.335,160,SEVERE,"Error saving coverage data",jscover.server.InstrumentingRequestHandler,
java.lang.RuntimeException: org.mozilla.javascript.json.JsonParser$ParseException: Missing comma in array literal
	at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:436)
	at jscover.report.JSONDataMerger.mergeJSONCoverageStrings(JSONDataMerger.java:368)
	at jscover.report.JSONDataSaver.saveJSONData(JSONDataSaver.java:376)
	at jscover.server.InstrumentingRequestHandler.storeReport(InstrumentingRequestHandler.java:421)
	at jscover.server.InstrumentingRequestHandler.handlePostOrPut(InstrumentingRequestHandler.java:391)
	at jscover.server.HttpServer.run(HttpServer.java:418)
Caused by: org.mozilla.javascript.json.JsonParser$ParseException: Missing comma in array literal
	at org.mozilla.javascript.json.JsonParser.readArray(JsonParser.java:165)
	at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:60)
	at org.mozilla.javascript.json.JsonParser.readObject(JsonParser.java:119)
	at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:58)
	at org.mozilla.javascript.json.JsonParser.readObject(JsonParser.java:119)
	at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:58)
	at org.mozilla.javascript.json.JsonParser.parseValue(JsonParser.java:44)
	at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:412)
	... 5 more

20170117 5:02:09.336,160,FINE,"Sending response status:200 OK mime:text/plain",jscover.server.HttpServer,
20170117 5:02:09.336,160,FINEST,"Socket closed",jscover.server.HttpServer,
```

**Comment by tntim96** [comment]
> InstrumentingRequestHandler.java:421

Line 420 is `logger.finest(data);` - I guess you've replaced the actual data with `149882 bytes valid JSON`... 

Is it possible to send me those JSON files in the order they're sent so I can try merging in the same way?

**Comment by cobexer** [comment]
Yes I replaced the huge JSON with a short description.

I'm not sure what you expect to get from me, based on the log I had the exception happen on the first POST to /jscoverage-store thus I assume there is only the received data to persist and nothing to merge.

Looking at your IoUtils::toStringNoClose implementation I assume reading from the passed stream failed and resulted in an array that was only partially written and thus produced the bogus returned string. The assert statement below should have no effect because assertions are not enabled by default AFAIK.

**Comment by tntim96** [comment]
> I assume there is only the received data to persist and nothing to merge

But there's the log `Saving/merging JSON with existing JSON`, so it's definitely merging. I've noticed some of the logs appear twice. Is it possible that you're saving twice?

**Comment by cobexer** [comment]
I didn't modify the logs beyond redacting hostnames, IP Addresses, some HTTP Headers and deleting ~5 * 150k JSON / 0x00 bytes. 

I just realized from looking at the log time stamp that this is the log from the second CI run (that reuses the stored JSON data to add to it). So I will get the logs from the first execution to actually capture the execution that breaks the JSON hopefully - the logs above just had a broken jscoverage.json on disk already. 🤦‍

**Comment by cobexer** [comment]
While I couldn't reproduce this with manual testing my CI reproduced the error again and I have an idea what may be the problem:
* We typically call jscoverage_report in beforeunload (sometimes in unload).
* jscoverage_report submits the coverage data asynchronously
* Some annoying browser vendor (Google) decided that aborting XHRs is a really great idea to annoy developers who need to store data before unloading of a document (there were also talks to remove synchronous XHR...).
* --> depending on the timing the coverage content may be transmitted already or it may only be transmitted partially.
It looks like if the first request to store data is from Chrome and is only partially transmitted the JSON file will be corrupted.
I therefore believe there are the following Problems:
 * JSCover stores coverage data using asynchronous XHRs which would work fine if we were able to call this earlier and wait for completion - thats sadly not possible for us.
 * JSCover does not parse or validate uploaded JSON nor does it properly detect partial uploads

To fix this:
 * JSCover could use https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon and only fall back to XHR if sendBeacon is unavailable or fails
 * JSCover should never corrupt it's JSON data store on disk.

**Comment by tntim96** [comment]
> JSCover stores coverage data using asynchronous XHRs which would work fine if we were able to call this earlier and wait for completion - thats sadly not possible for us

If you are calling `jscoverage_report` then you should be able to wait. In web-driver you could do something like:
```Java
((JavascriptExecutor) webClient).executeScript("window.jscoverFinished = false;");
((JavascriptExecutor) webClient).executeScript("jscoverage_report('', function(){window.jscoverFinished=true;});");
    (new WebDriverWait(webClient, 10000))
        .until((ExpectedCondition<Boolean>) d -> (Boolean)((JavascriptExecutor) webClient).executeScript("return window.jscoverFinished;"));
```

**Comment by cobexer** [comment]
Sadly I don't have WebDriver nor do I have a hook in the test tool where I could do it that way.

Besides IMO calling jscoverage_report should be handled by JSCover internally when in webserver mode.

**Comment by tntim96** [comment]
> Besides IMO calling jscoverage_report should be handled by JSCover internally when in webserver mode.

It depends what you mean by 'handled'. It does save what was submitted which works in the majority of cases. If you want it to verify the JSON, then, apart from adding overhead most users don't need, it doesn't solve your problem. Users can easily log the data to determine if there is a JSON error.

> Sadly I don't have WebDriver nor do I have a hook in the test tool where I could do it that way.

I was only using WebDriver as an example. How are you able to call `jscoverage_report`?

**Comment by cobexer** [comment]
> It depends what you mean by 'handled'.

Like the code below, aka transparent for the user. But this is just a note, I have no problem calling `jscoverage_report` before closing the window I just need that to actually work.

> If you want it to verify the JSON, then, apart from adding overhead most users don't need

Why is it ok that an aborted request can corrupt the jscoverage.json on the server?

> How are you able to call `jscoverage_report`?

We call `jscoverage_report` in the `beforeunload` event handler (we use jQuery) this worked really well up to now :)
```javascript
$(window).on('beforeunload', function() {
  if (window.jscoverage_report) {
    jscoverage_report();
  }
});
```

**Comment by tntim96** [comment]
You can just replace the `jscoverage_report` call with the old JSCover synchronous call:
```JavaScript
    var request;
      if (window.XMLHttpRequest) {
        request = new XMLHttpRequest();
      } else if (window.ActiveXObject) {
        request = new ActiveXObject("Microsoft.XMLHTTP");
      }
    };

    request.open('POST', '/jscoverage-store', false);
    request.setRequestHeader('Content-Type', 'application/json');
    request.send(jscoverage_serializeCoverageToJSON());
```
...however, the [synchronous XMLHttpRequest call has being deprecated](https://github.com/tntim96/JSCover/issues/232), so cannot be relied upon indefinitely.

Another approach might be to store the coverage data in the browser's local storage, and retrieve it later with some other mechanism if that's possible.

**Comment by cobexer** [comment]
I did not realize `jscoverage_serializeCoverageToJSON` is accessible for us...

So I will need to reimplement `jscoverage_report` and will need to hope that the data always reaches the JSCover server completely?

> ...however, the synchronous XMLHttpRequest call has been deprecated, so cannot be relied upon indefinitely.

Yes I know, which is why I posted the sendBeacon documentation above, because that is supposed to work for some of the use-cases sync XHR were used for in the past.
