### ISSUE TITLE
Wrong 'position' values

### ISSUE THREAD

**Issue by bancer** [tntim96/JSCover#243]
According to https://tntim96.github.io/JSCover/manual/manual.xml  position means "Branch starts n chars in from line (future use)". It seems that position values are wrong. F.ex. the coverage report for the following code have positions 171 and 179 but the code lines are much shorter than that. 

```
19		check: function( event, ui ) {
20			'use strict';
21			var min = parseInt($('#RestaurantBookingPax').attr('aria-valuemin'));
22			var max = parseInt($('#RestaurantBookingPax').attr('aria-valuemax'));
23			if (ui.value === undefined || ui.value <= min) {
                        ....
```

```
...
      "branchData":{
         "23":[
            null,
            {
               "position":171,
               "nodeLength":41,
               "src":"ui.value === undefined || ui.value <= min",
               "evalFalse":0,
               "evalTrue":0
            },
            {
               "position":171,
               "nodeLength":22,
               "src":"ui.value === undefined",
               "evalFalse":0,
               "evalTrue":0
            },
            {
               "position":197,
               "nodeLength":15,
               "src":"ui.value <= min",
               "evalFalse":0,
               "evalTrue":0
            }
         ],
...
```

**Comment by tntim96** [comment]
I guess I could either remove this feature and the documentation, or update the documentation to match that in Rhino's [AstNode.getPosition](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/ast/AstNode.java#L160) - which I don't think is useful to the end user.

Were you hoping to use this?

**Comment by stevepeak** [comment]
Thank you @tntim96 for your time and help. I'm from Codecov and we would love to show partial line coverage for JSCover which could look like this beautiful report: https://codecov.io/gh/babel/babylon/src/6cb0235/src/parser/expression.js#L804

The reason for this issue is to change the data format to what column(s) are covered or not. The relative position is, IMO, useless information. What would be much more valuable is column data. Which is what Istanbul offers.

Here is an example

```js
     if (ui.value <= min) {
123456789....
         | <= 10  24 =>|
````

```json
"branchData":{
   "23":[
      null,
      {
         "columnStart": 10,
         "columnEnd": 24,
         "src":"ui.value <= min",
         "evalFalse":0,
         "evalTrue":0
      },
```

I'm happy to provide more information or details if necessary. Thank you again and I hope you accept these changes so we can improve our coverage reports for JSCover.

**Comment by tntim96** [comment]
Sure. This is implemented in Rhino, but I'll see if can extract that information or create a ticket in Rhino to make it available. Any help welcome.

**Comment by stevepeak** [comment]
Awesome!! Please let me know where I can help.

**Comment by tntim96** [comment]
It looks like it's easiest to go with the absolute position (i.e. the position from the start of the file) which I think would be OK. I'll wait for you're feedback before committing, but you can test on a [ZIP of this build](jscover.sourceforge.net/JSCover-1.0.26-SNAPSHOT.zip), or use the latest maven snapshot (JSCover-1.0.26-20170210.225050-5).

```XML
<dependency>
    <groupId>com.github.tntim96</groupId>
    <artifactId>JSCover</artifactId>
    <version>1.0.26-SNAPSHOT</version>
</dependency>
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

Let me know what you think. If all OK, I'll start preparing a release.

I'm also interested in linking to your documentation from the JSCover manual. Is there a specific integration documentation page that's best? Do you list supported integrations?

**Comment by tntim96** [comment]
Actually, as I have access to the source JS file, I should be able to calculate line position which I could use in the JSCover report, and remove the 'src' attribute in the JSON, i.e.

```
    "src":"source",  //Branch source to easily identify conditions in report
```

**Comment by tntim96** [comment]
Actually, as I have access to the source JS file, I should be able to calculate line position which I could use in the JSCover report, and remove the 'src' attribute in the JSON, i.e.

```
    "src":"source",  //Branch source to easily identify conditions in report
```

**Comment by tntim96** [comment]
I've committed the fix but haven't released yet, but you can test on a [ZIP of this build](jscover.sourceforge.net/JSCover-1.0.26-SNAPSHOT.zip), or use the latest maven snapshot (JSCover-1.0.26-20170211.021316-6).

```XML
<dependency>
    <groupId>com.github.tntim96</groupId>
    <artifactId>JSCover</artifactId>
    <version>1.0.26-SNAPSHOT</version>
</dependency>
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

Let me know what you think. If all OK, I'll start preparing a release.

I'm also interested in linking to your documentation from the JSCover manual. Is there a specific integration documentation page that's best? Do you list supported integrations?

**Comment by tntim96** [comment]
> I should be able to calculate line position which I could use in the JSCover report, and remove the 'src' attribute in the JSON

This is now done as well.

**Comment by tntim96** [comment]
I've released this now in version 1.1.0. Let me know if you find any issues.

**Comment by stevepeak** [comment]
Thank you @tntim96 excellent job!

@bancer  can you upgrade and send a new commit to Codecov? We can review the reports to see if everything lines up now. Thank you

**Comment by bancer** [comment]
@tntim96 Regarding documentation: I used [this](http://julianhigman.com/blog/2013/07/23/testing-javascript-with-qunit-phantomjs-and-jscover/) blog for setting up the tests on Jenkings and [Codecov Bash Uploader](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) in ant.xml:
```
	<target name="codecov-js">
		<exec executable="sh" failonerror="true">
			<arg value="-c" />
			<arg value="curl -s https://codecov.io/bash | bash -s - -t CODECOV_TOKEN -s /tmp/jscoverage -cF javascript" />
		</exec>
	</target>
```
