### ISSUE TITLE
JSCover not capturing the coverage data.

### ISSUE THREAD

**Issue by abhibang** [tntim96/JSCover#248]
Using JSCover to capture Java Script coverage of my application.
Some brief about my application:
 Our application is not a pure JS application. It has java components on back end. 

Currently JS cover is not collecting the reports with below approaches 
The application war is hosted on web server (Glassfish). 

**Approach1:**
To obtain the JS code coverage I've started JS Cover as specified in manual:
_java -jar target/dist/JSCover-all.jar -ws --document-root=<FolderPathContainingAllMyApplicationJSSourceFiles> --report-dir=target_

Accessed my application url in http://localhost:8080/jscoverage.html
1. Via opening it <applicationUrl> in frame, here the first screen of my application does not show up
2. Via opening it <applicationUrl> in window, here my application opens up but on further navigation, after clicking on store Report, the coverage data is not collected. 

Where in the reports have coverage collected for the demo app.

**Approach2:**
Used and modified WebDriverGeneralProxyTest (added my application url and navigation in @Test shouldRunExampleAndStoreResultProgrammatically) present in https://github.com/tntim96/JSCover-samples to collect the coverage data making selenium to do the navigations. 
- Modified @Test shouldRunExampleAndStoreResultProgrammatically 
`@Test
    public void shouldRunExampleAndStoreResultProgrammatically() {
        deleteJSON("/no-frames");
        driver.get("myApplicationUrl");
        userLogsInApplication();
        doNaviagtion();
        ((JavascriptExecutor) driver).executeScript("window.jscoverFinished = false;");
        ((JavascriptExecutor) driver).executeScript("jscoverage_report('no-frames', function(){window.jscoverFinished=true;});");
        (new WebDriverWait(driver, 10))
                .until((ExpectedCondition<Boolean>) d -> (Boolean) ((JavascriptExecutor) driver).executeScript("return window.jscoverFinished;"));
        verifyCoverage("/no-frames");
    }`
- selenium script fails to execute the js snippet ((JavascriptExecutor) driver).executeScript("jscoverage_report('no-frames', function(){window.jscoverFinished=true;});");
- And when we comment out the all the js snippet, on teardown report dir does not have reports files.

Please guide me if I'm doing something wrong.

**Comment by tntim96** [comment]
If you want to gather code coverage while testing your application on Glassfish (or any server) you can't use the [server-mode](https://tntim96.github.io/JSCover/manual/manual.xml#serverMode) (i.e. `-ws` switch). That is for server static test files like Jasmine and QUnit.

You can use [proxy-mode](https://tntim96.github.io/JSCover/manual/manual.xml#proxyMode), but it doesn't work over SSL, and I generally recommend using [file-system mode](https://tntim96.github.io/JSCover/manual/manual.xml#fileMode).

To do this you need to (from the top of my head):
# Instrument the JS files you want (normally using the [HTML5 local storage switch](https://tntim96.github.io/JSCover/manual/manual.xml#localStorage) )
# Start your application with the instrumented JS files replacing the original ones
# Run your tests
# [Save your coverage data](https://tntim96.github.io/JSCover/manual/manual.xml#fileSystemSave)

This process is documented in https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system
