### ISSUE TITLE
JSCover is changing original lines of code .

### ISSUE THREAD

**Issue by hiteshsardana99** [tntim96/JSCover#250]
Whenever i am creating instrument code of javascript files. In one file , © ( copy right symbol )  and ® ( Registered trademark symbol) is changing into  '\xc2\xa9\xc2\xae'
![changedcontent](https://cloud.githubusercontent.com/assets/25656132/26150520/515cf35a-3b1c-11e7-8a50-023a5e16e807.PNG)

@©® is converting into @\xc2\xa9\xc2\xae .

Original Non-Instrumented file ->
![originalcode](https://cloud.githubusercontent.com/assets/25656132/26150451/0246c2f0-3b1c-11e7-944a-d9fa1eea867e.PNG)

Please help me out.

**Comment by tntim96** [comment]
Those values are the [hexadecimal](http://www.ascii.cl/htmlcodes.htm) equivalents and shouldn't be a problem in your coverage tests.

If you are finding the escaping is not correct, make sure you are using the correct [file encoding](http://tntim96.github.io/JSCover/manual/manual.xml#encoding).

**Comment by hiteshsardana99** [comment]
Hello Sir,
Can we change the name of jscoverage_serializeCoverageToJSON() function? 
Actually this function name is not in camel case format therefore I want to change its name to jsCoverageSerializeCoverageToJSON() .

**Comment by tntim96** [comment]
That isn't configurable, but you could create your own by copying the current one. Changing the name would break it for other users.

Why do you need it changed?

**Comment by hiteshsardana99** [comment]
How can i create my own function ?
As I earlier told you that name of this function name is not according to the rules of camel casing.

**Comment by tntim96** [comment]
> How can i create my own function ?

I don't know your set up. Maybe you can't.

> As I earlier told you that name of this function name is not according to the rules of camel casing.

But why does that matter?

**Comment by hiteshsardana99** [comment]
I have to consider all the these things before writing code in my project. 

Anyway, I want to clarify few things.
When we use this function to fetch the report then where this function exist? . 
I have seen this function in every instrumented files or in jscoverage.js file.

**Comment by tntim96** [comment]
It depends on your set-up. Which [example](https://github.com/tntim96/JSCover/tree/master/examples) will your project most closely match?

**Comment by hiteshsardana99** [comment]
I am using file-system mode .

**Comment by tntim96** [comment]
Take a look at [localStorage-file-system](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system) and [phantomJS-file-system](https://github.com/tntim96/JSCover/tree/master/examples/phantomJS-file-system) then. They are working samples and should have enough code to get you started.
