### ISSUE TITLE
jscoverage_report doesn't work with PhantomJS after upgrade

### ISSUE THREAD

**Issue by TiTi** [tntim96/JSCover#251]
Hello,

I've upgraded JSCover from 1.0.18 to 1.1.0 but the coverage file is not written anymore 😭 
I'm using PhantomJS and using the classic:
```
var result = page.evaluate(function(jscover, pageName)
{
	jscoverage_report('phantom_' + pageName);
	...
}, jscover, pageName);
```

After digging out changelogs, other issues, ... 
I've discovered I can call `jscoverage_serializeCoverageToJSON()` myself and store it somewhere with `fs.write` (which works). But I'd like to let JSCover do it because I'm already specifying `--report-dir=` on JSCover command line.

I've discover that `jscoverage_report` from report.js of the target\dist\JSCover-all.jar is now asynchronous, thus explaining the change of behavior. But no error so a little bit tricky to understand.
Also not clear enough in the changelog...

How can I wait the end of `jscoverage_report` with PhantomJS? The documentation is not up to date regarding this.
With WebDriver you recommend to set & wait for `window.jscoverFinished` but how to do it with PhantomJS?

Edit: ok i managed to do it by re-using the "waitFor" helper.
For thoses interested:

```
var result = page.evaluate(function(jscover, pageName)
{
	jscoverage_report('phantom_' + pageName, function()
	{
		window.jscoverFinished = true;
	});
	...
}, jscover, pageName);

waitFor(function()
{
	return page.evaluate(function()
	{
		return window.jscoverFinished;
	});
},
function ()
{
	//console.log("real end");
	phantom.exit((parseInt(failedNum, 10) > 0) ? 1 : 0);
},
/* i have an "onError" callback in my run-jscover-qunit.js
function (msg)
{
	console.error(msg);
},*/
1000);
console.log("end");
//phantom.exit((parseInt(failedNum, 10) > 0) ? 1 : 0); // We have to wait for jscoverage_report end
```

And then PhantomJS wait properly that the coverage report is generated :-)

Indeed the code is simpler by using `jscoverage_serializeCoverageToJSON()` and `fs.write`, but you have to specify the report-dir on the run-jscover-qunit.js command line...

This ticket can be close. I manage to figure it out why typing it and I guess it could help others...

**Comment by tntim96** [comment]
Quick answer is that you can provide a callback function. You can use this to indicate when it is finished. I'll post an example here soon-ish and add an example to the documentation

> `jscoverage_report`...is now asynchronous...not clear enough in the changelog..

Yes, that changed in [1.0.25](https://github.com/tntim96/JSCover/blob/master/History.md#1025--2016-12-13) - I'll bold that note and add that this will require most users to make a code change.

> How can I wait the end of jscoverage_report with PhantomJS? The documentation is not up to date regarding this.

I haven't really documented that, and you're right, you can just call `jscoverage_serializeCoverageToJSON()` as done in the [phantomJS-file-system](phantomJS-file-system) and [phantomJS-server](https://github.com/tntim96/JSCover/tree/master/examples/phantomJS-server) examples using [run-jscover-jasmine2.js](https://github.com/tntim96/JSCover/blob/master/src/test/javascript/lib/PhantomJS/run-jscover-jasmine2.js) and [run-jscover-qunit.js](https://github.com/tntim96/JSCover/blob/master/src/test/javascript/lib/PhantomJS/run-jscover-qunit.js)

**Comment by tntim96** [comment]
I've done the following:

- [Changelog made clearer  for 1.0.25](https://github.com/tntim96/JSCover/blob/master/History.md#1025--2016-12-13)
- Updated [the documentation for programmatic report storage](http://tntim96.github.io/JSCover/manual/manual.xml#jsReportStorage)
- Updated [the documentation for Phantom JS report saving](http://tntim96.github.io/JSCover/manual/manual.xml#automatingPhantomJS)
- Update example  [phantomJS-server](https://github.com/tntim96/JSCover/tree/master/examples/phantomJS-server) using [run-jscover-qunit.js](https://github.com/tntim96/JSCover/blob/master/src/test/javascript/lib/PhantomJS/run-jscover-qunit.js)
- Update [run-jscover-jasmine2.js](https://github.com/tntim96/JSCover/blob/master/src/test/javascript/lib/PhantomJS/run-jscover-jasmine2.js)

Let me know if you see any issues.

**Comment by TiTi** [comment]
👍
