### ISSUE TITLE
Question about using --only-instrument-reg

### ISSUE THREAD

**Issue by guru-carmatec** [tntim96/JSCover#252]
Hi,
  
   I have to instrument one file inside a directory and all files inside another directory excluding 2 subdirectories inside it. Below is my folder structure.

profile/
- vendor/
-- webTool/Backend/js/   (Have to instrument common.js from here)
-- /libraries/Plugins/js/    (Have to instrument all files and folders here except Chosen and DataTables subfolders)

I tried searching for an example for --only-instrument-reg, but couldn't find any.

Can anyone please help me on how to write a regular expression to achieve the above? 

Thanks in advance for anyhelp.

Thank You.

**Comment by tntim96** [comment]
There is an option, `-regex-test`, specifically to test your regular expressions. Try something like:
```
java -jar JSCover-all.jar -regex-test "/a.*" "/ab"
```
