### ISSUE TITLE
Getting jscoverage_report is not defined for https url in WebDriverGeneralProxyTest

### ISSUE THREAD

**Issue by mayankdevapplift** [tntim96/JSCover#254]
I have to calculate the code coverage of an app in which I want to access the url which is ssl enabled. Is there any way to do this?

Currently I am getting jscoverage_report is not defined

**Comment by tntim96** [comment]
Yes, but not using the proxy which doesn't support SSL. You have to pre-instrument the JavaScript, deploy them in your application, and then extract the coverage data as done in the [localStorage-file-system](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system) example.
