### ISSUE TITLE
How to use jsCover in jenkins? 

### ISSUE THREAD

**Issue by wl020814** [tntim96/JSCover#262]
hello,I'd like to test the jsCover function in jenkins. is there any examples or suggestions? i see the user manual , but there is only a few words about jenkins, just tell me to avoid port problems. i am not sure  whether i can just use the bat cmd in your examples to realize the function. which is the best mode to use in jenkins, Server,proxy or file-System. Thanks for your help.

**Comment by tntim96** [comment]
You might find #39 useful

**Comment by wl020814** [comment]
Could U give me some suggestion about Selenium? i see U put selenium-ide.html in the localStorage-file-system diretory. how can i use it. Thank U for help!

**Comment by tntim96** [comment]
It's in the Readme.md. The command is `rspec selenium-ide.rb`.

**Comment by wl020814** [comment]
I wonder that 
  Is your ruby example test work in linux or windows system, or the two system is all ok. 
 thank U!

**Comment by tntim96** [comment]
It should work on both, but I tested on Linux.

**Comment by wl020814** [comment]
i got this promblem,when i check the source code in server mode, it display the instructed code,not the original.  My Os is Win7-64 , ie8.and in ubuntu System， i don't get the same problem. Does it have sth to do with the system or browser？ Thank U!
![jscover](https://user-images.githubusercontent.com/11747432/30794914-87748ffa-a1fd-11e7-9a88-001da868dc5c.png)

**Comment by tntim96** [comment]
I'm guessing it's the new line character. Should be easy for me to fix.

**Comment by tntim96** [comment]
It looks like you've copied the instrumented code to your `<reports-dir>/original-src` directory.

**Comment by wl020814** [comment]
Thank U！
