### ISSUE TITLE
Conditional compilation directives

### ISSUE THREAD

**Issue by syno2flickr** [tntim96/JSCover#264]
Hi,

I'm facing an issue with the instrumentation mode. I'm using the ExtJs conditional compilation directive [\<debug\>...\</debug\>](https://docs.sencha.com/cmd/guides/advanced_cmd/cmd_compiler_reference.html#advanced_cmd-_-cmd_compiler_reference_-_conditional_compilation) in my app:
```
....
// Loading of all translations
var extJsFile = Ext.util.Format.format("resources/locale/ext-locale-{0}.js", locale);
// <debug>
extJsFile = Ext.util.Format.format("ext/classic/locale/overrides/{0}/ext-locale-{0}.js", locale);
// </debug>
if (locale !== 'en'){
     Ext.Loader.loadScript({url: extJsFile});
}
...
```
But after the instrumentation is done the directive is missing like any other comments:
```
...
 _$jscoverage['/app/Application.js'].lineData[110]++;
var extJsFile = Ext.util.Format.format("resources/locale/ext-locale-{0}.js", locale);
_$jscoverage['/app/Application.js'].lineData[111]++;
extJsFile = Ext.util.Format.format("ext/classic/locale/overrides/{0}/ext-locale-{0}.js", locale);
_$jscoverage['/app/Application.js'].lineData[113]++;
if (visit17_116_1(locale !== 'en')) {
     _$jscoverage['/app/Application.js'].lineData[115]++;
    Ext.Loader.loadScript({
         url: extJsFile
    });
}
...
```
How can I manage this? Thanks
I'm using JsCover v1.1.0

**Comment by tntim96** [comment]
Looks like this isn't possible until https://github.com/google/closure-compiler/issues/164 is fixed

**Comment by syno2flickr** [comment]
Thank you for the answer. I have to come with the same conclusion. I definitely haven't any hope this will change. I will find another way.
