### ISSUE TITLE
"Error saving coverage data",jscover.server.InstrumentingRequestHandler, com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 8376000 path $..functionData[35]

### ISSUE THREAD

**Issue by weiding111** [tntim96/JSCover#267]
There are error messages as followings when I use jscover and adding the option "--include-unloaded-js" in proxy mode.

start proxy command - 
java -jar JSCover-all-2.0.3.jar -ws --proxy --port=3128 --report-dir=./jscover/output --document-root=/Users/weiding/Git/fmw-bi-qafmk/bitools-utils/podapiutil/coverage/carbs/js/plugins --local-storage --include-unloaded-js

I do not have any idea about this issue. Is it a bug when saving the coverage data?

Detailed error messages- 
20180403 11:20:00.439,227,SEVERE,"Error saving coverage data",jscover.server.InstrumentingRequestHandler,
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 8370739 path $..branchData.5[1].evalFalse
	at com.google.gson.Gson.fromJson(Gson.java:902)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:404)
	at jscover.report.JSONDataSaver.saveJSONData(JSONDataSaver.java:382)
	at jscover.server.InstrumentingRequestHandler.storeReport(InstrumentingRequestHandler.java:421)
	at jscover.server.InstrumentingRequestHandler.handlePostOrPut(InstrumentingRequestHandler.java:391)
	at jscover.server.HttpServer.run(HttpServer.java:418)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 8370739 path $..branchData.5[1].evalFalse
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1017)
	at com.google.gson.stream.JsonReader.nextName(JsonReader.java:787)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:61)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 8 more

20180403 11:25:32.769,441,SEVERE,"Error saving coverage data",jscover.server.InstrumentingRequestHandler,
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 8376000 path $..functionData[35]
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:404)
	at jscover.report.JSONDataSaver.saveJSONData(JSONDataSaver.java:382)
	at jscover.server.InstrumentingRequestHandler.storeReport(InstrumentingRequestHandler.java:421)
	at jscover.server.InstrumentingRequestHandler.handlePostOrPut(InstrumentingRequestHandler.java:391)
	at jscover.server.HttpServer.run(HttpServer.java:418)
Caused by: java.io.EOFException: End of input at line 1 column 8376000 path $..functionData[35]
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:467)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:60)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 8 more

**Comment by tntim96** [comment]
First thing to check is the [URI to file path translation](http://tntim96.github.io/JSCover/manual/manual.xml#proxyURIToFilePathTranslation) or you can try running without the `--include-unloaded-js` just to see if this is the cause.

If that's not the problem, I'd probably have to see the JSON what's causing the error.

**Comment by weiding111** [comment]
I tried running without the |--include-unloaded-js, there is no issue 
without ||--include-unloaded-js. This error only appears when running 
with |||--include-unloaded-js.

|Thanks,
Wei
|

**Comment by tntim96** [comment]
In that case, please read the [URI to file path translation documentation](http://tntim96.github.io/JSCover/manual/manual.xml#proxyURIToFilePathTranslation) - it may need some tweaking. Also take a look in the log file to make sure there's no error there.

Also, you might be able to narrow down which "unloaded-source-file" is causing the problem by progressively removing files. I can add logging to assist with this, and can tailor that to whatever you need. Let me know.

**Comment by weiding111** [comment]
Is it possible to get more logs info, like which js file cause the error?  Is the error due to the file under --document-root is not with the expected format?

**Comment by tntim96** [comment]
Can you put the JSON somewhere for me to look at?

**Comment by weiding111** [comment]
Which json file do you mean? As for my side, I just start the jscover server by proxy mode, and running the selenium automated tests by firefox. Then the error messages appear in the jscover.log. There is no json file under --report-dir, there are jscover.log,  jscover.log.lck and original-src folder under --report-dir.

**Comment by weiding111** [comment]
I call the following code in the framework.
Generate the reprot - 
`((JavascriptExecutor)(auto.getDriver())).executeScript(
        			"if(window.jscoverage_report)jscoverage_report();");`

Firefox Profile setting - 
`firefoxProfile.setPreference("network.proxy.http", "localhost");
  firefoxProfile.setPreference("network.proxy.http_port", "3128");`

There is jscoverage.json under --report-dir without "--unloaded-source-file"

**Comment by tntim96** [comment]
> Is it possible to get more logs info, like which js file cause the error?

If you set the logging level to `FINE` or `jscover.util.FileScanner.level = FINE` as described in the [documentation section on logging](http://tntim96.github.io/JSCover/manual/manual.xml#logging), you should see something like `20180404 20:45:24.143,18,FINE,"Adding path test-simple.js",jscover.util.FileScanner`. Hopefully you'll notice if something is there that shouldn't be.

> Is the error due to the file under --document-root is not with the expected format?

I suspect so.

**Comment by tntim96** [comment]
> There are too many js files has this kind of warning messages (more than 10000), so I could not use the way of filtering these source files from --document-root dir. Is there any other way to make it work?

What about excluding by regular expression using `--no-instrument-reg`?

**Comment by weiding111** [comment]
The point is most of them are the files we need to map to URI files, if I exclude them, there are many source files are missing, and js coverage report will lost the area that automated tests not covered.

**Comment by tntim96** [comment]
OK. Can you provide a sample of the code that isn't parsed correctly and provide details of what tools you use with the source currently?

**Comment by weiding111** [comment]
The source files are provided by other DEV, I use selenium webdriver to implement automated tests. So I am not sure what tools the DEV uses. Here is an sample of the code that isn't parsed correctly.
`// Copyright © 1997, 2018, Oracle and/or its affiliates
// All rights reserved.

/**
 * @fileoverview This file provides catalog query card
 */

/**
 * @module obitech-dssdataset/catalogsourcequerycard
 */
define(['obitech-framework/jsx',
        'ojs/ojcore',
        'jquery',
        'knockout',
        'obitech-dssdataset/catalogsourcequerypane',
        'obitech-dssdataset/basedatasourcequerycard',
        //i18n
        'ojL10n!obitech-dssconnection/nls/messages',
        //---Styles: no params---//
        'skin',
        'skin!css!obitech-dssconnection/connectioncardstyles'],
function(jsx,
         oj,
         $,
         ko,
         catalogsourcequerypane,
         basedatasourcequerycard,
         messages) {

   'use strict';

   jsx.assertAllNotNull(arguments, "obitech-dssdataset/catalogsourcequerycard resources");

   /**
    * Return object for AMD module
    * @exports obitech-dssdataset/catalogsourcequerycard
    */
   var catalogsourcequerycard = {};

   /**
   * @constructor
   * @param {string} sID the component's unique ID
   * @param {string} sDispalyName The component's display name
   * @param {string} sOrigin A short text string describing the page that constructed this catalogsourcequerycard
   * @param {module:obitech-report/datasourcedialog#DataSourceDialog} oDialog the dialog own this card
   * @param {object} oOptions the options
   * @extends {module:obitech-dssdataset/basedatasourcequerycard#BaseDataSourceQueryCard}
   */
   function CatalogSourceQueryCard(sID, sDispalyName, sOrigin, oDialog, oOptions) {
      jsx.assertObject(oOptions, "oOptions");
      jsx.assertObject(oOptions.oConnection, "oOptions.oConnection");

      CatalogSourceQueryCard.baseConstructor.call(this, sID, sDispalyName, sOrigin, oDialog, oOptions);

      // Register catalog query pane
      var oCatalogQueryPane = new catalogsourcequerypane.CatalogSourceQueryPane("CatalogSourceQueryPane", "CatalogSourceQueryPane", "CatalogSourceQueryCard", this, oOptions, oDialog);
      this._registerChildHostedComponent(oCatalogQueryPane);
      this.setDatasourceQueryPane(oCatalogQueryPane);
   }
   jsx.extend(CatalogSourceQueryCard, basedatasourcequerycard.BaseDataSourceQueryCard);

   /**
    * @inheritdoc
    * {@link module:obitech-report/basedatasourcecard#BaseDataSourceCard#getDefaultTitle}
    */
   CatalogSourceQueryCard.prototype.getDefaultTitle = function(){
      return messages.CREATE_NEW_SOURCE_ANALYSIS.format(this.getConnection().name);
   };

   /**
    * Implementation of the definitions.DSSDataset_XP extension point
    * @param {string} sID the component's unique ID
    * @param {string} sDisplayName the component's display name
    * @param {string} sOrigin A short text string describing the page that constructed this catalogsourcequerycard
    * @param {module:obitech-report/datasourcedialog#DataSourceDialog} oDialog the dialog own this card
    * @param {object} the connection model
    * @returns {CatalogSourceQueryCard} an instance of a CatalogSourceQueryCard
    * @funcdataoDition createCardInstance
    * @memberof module:obitech-dssdataset/catalogsourcequerycard
    */
   catalogsourcequerycard.createInstance = function(sID, sDispalyName, sOrigin, oDialog, oConnection) {
      return new CatalogSourceQueryCard(sID, sDispalyName, sOrigin, oDialog, oConnection);
   };

   catalogsourcequerycard.CatalogSourceQueryCard = CatalogSourceQueryCard;

   return catalogsourcequerycard;
});
`
Here is the error message - 

20180409 13:54:12.438,212,WARNING,"illegal use of unknown JSDoc tag "exports"; ignoring it, sourceName: report/obitech-dssdataset/catalogsourcequerycard.js, line: 36 lineOffset: 6",jscover.instrument.SourceProcessor,
20180409 13:54:12.438,212,WARNING,"Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information., sourceName: report/obitech-dssdataset/catalogsourcequerycard.js, line: 45 lineOffset: 19",jscover.instrument.SourceProcessor,
20180409 13:54:12.438,212,WARNING,"Bad type annotation. expecting a variable name in a @param tag. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information., sourceName: report/obitech-dssdataset/catalogsourcequerycard.js, line: 45 lineOffset: 19",jscover.instrument.SourceProcessor,
20180409 13:54:12.438,212,WARNING,"Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information., sourceName: report/obitech-dssdataset/catalogsourcequerycard.js, line: 47 lineOffset: 21",jscover.instrument.SourceProcessor,
20180409 13:54:12.438,212,WARNING,"illegal use of unknown JSDoc tag "inheritdoc"; ignoring it, sourceName: report/obitech-dssdataset/catalogsourcequerycard.js, line: 63 lineOffset: 6",jscover.instrument.SourceProcessor,
20180409 13:54:12.438,212,WARNING,"Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information., sourceName: report/obitech-dssdataset/catalogsourcequerycard.js, line: 75 lineOffset: 20",jscover.instrument.SourceProcessor,
20180409 13:54:12.438,212,WARNING,"Bad type annotation. expecting a variable name in a @param tag. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information., sourceName: report/obitech-dssdataset/catalogsourcequerycard.js, line: 75 lineOffset: 20",jscover.instrument.SourceProcessor,
20180409 13:54:12.439,212,WARNING,"illegal use of unknown JSDoc tag "funcdataoDition"; ignoring it, sourceName: report/obitech-dssdataset/catalogsourcequerycard.js, line: 78 lineOffset: 6",jscover.instrument.SourceProcessor,

**Comment by weiding111** [comment]
I used the json-path-2.4.0.jar

**Comment by tntim96** [comment]
I just tried with the current JSCover which uses closure-compiler `v20180402`.

Can you try again with http://jscover.sourceforge.net/JSCover-all.jar or with maven:
```XML
<!--- Configure repository --->
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
<!--- Configure snapshot --->
<dependency>
    <groupId>com.github.tntim96</groupId>
    <artifactId>JSCover</artifactId>
    <version>2.0.5-SNAPSHOT</version>
</dependency>
```

**Comment by tntim96** [comment]
Actually - I've just released `2.0.5` anyway, so you can try that.

**Comment by weiding111** [comment]
It encountered a 404 error when I click the link  http://jscover.sourceforge.net/JSCover-all.jar.

**Comment by weiding111** [comment]
I used the jscover-all.jar file against release 2.0.5, the error is not the com.google.gson.stream.MalformedJsonException, the new exception "com.google.gson.JsonSyntaxException: java.io.EOFException" appears. 

Here is the log -

......
20180412 14:01:10.023,367,FINE,"No branchInstrumentor condition changes after parse 1",jscover.instrument.SourceProcessor,
20180412 14:01:10.024,367,FINE,"Adding empty coverage for file: '/Users/weiding/Git/fmw-bi-qafmk/bitools-utils/podapiutil/coverage/carbs/js/plugins/application/obitech-share/nls/ru/exportscreenshotconf.messages.js' URI: 'obitech-share/nls/ru/exportscreenshotconf.messages.js'",jscover.instrument.UnloadedSourceProcessor,
20180412 14:01:10.024,367,FINE,"No branchInstrumentor condition changes after parse 1",jscover.instrument.SourceProcessor,
20180412 14:01:10.024,367,FINE,"Adding empty coverage for file: '/Users/weiding/Git/fmw-bi-qafmk/bitools-utils/podapiutil/coverage/carbs/js/plugins/application/obitech-appservices/nls/el/messagecomponent.messages.js' URI: 'obitech-appservices/nls/el/messagecomponent.messages.js'",jscover.instrument.UnloadedSourceProcessor,
20180412 14:01:10.025,367,FINE,"No branchInstrumentor condition changes after parse 1",jscover.instrument.SourceProcessor,
20180412 14:01:10.025,367,FINE,"Adding empty coverage for file: '/Users/weiding/Git/fmw-bi-qafmk/bitools-utils/podapiutil/coverage/carbs/js/plugins/application/obitech-appservices/nls/he/cspmanager.messages.js' URI: 'obitech-appservices/nls/he/cspmanager.messages.js'",jscover.instrument.UnloadedSourceProcessor,
20180412 14:01:10.025,367,FINE,"No branchInstrumentor condition changes after parse 1",jscover.instrument.SourceProcessor,
20180412 14:01:10.025,367,FINE,"Adding empty coverage for file: '/Users/weiding/Git/fmw-bi-qafmk/bitools-utils/podapiutil/coverage/carbs/js/plugins/application/obitech-appservices/nls/ro/messagecomponent.messages.js' URI: 'obitech-appservices/nls/ro/messagecomponent.messages.js'",jscover.instrument.UnloadedSourceProcessor,
20180412 14:01:10.025,367,FINE,"No branchInstrumentor condition changes after parse 1",jscover.instrument.SourceProcessor,
20180412 14:01:10.026,367,FINE,"Adding empty coverage for file: '/Users/weiding/Git/fmw-bi-qafmk/bitools-utils/podapiutil/coverage/carbs/js/plugins/application/obitech-appservices/nls/pt/gadgetfactory.messages.js' URI: 'obitech-appservices/nls/pt/gadgetfactory.messages.js'",jscover.instrument.UnloadedSourceProcessor,
20180412 14:01:10.026,367,FINE,"No branchInstrumentor condition changes after parse 1",jscover.instrument.SourceProcessor,
20180412 14:01:12.220,367,INFO,"Saving/merging JSON with unloaded JavaScript JSON",jscover.report.JSONDataSaver,
20180412 14:01:12.220,367,INFO,"Saving/merging JSON with unloaded JavaScript JSON",jscover.report.JSONDataSaver,
20180412 14:01:12.310,367,SEVERE,"Error saving coverage data",jscover.server.InstrumentingRequestHandler,
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 8352906 path $..branchData.3[187].nodeLength
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)
        at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:404)
        at jscover.report.JSONDataSaver.saveJSONData(JSONDataSaver.java:382)
        at jscover.server.InstrumentingRequestHandler.storeReport(InstrumentingRequestHandler.java:421)
        at jscover.server.InstrumentingRequestHandler.handlePostOrPut(InstrumentingRequestHandler.java:391)
        at jscover.server.HttpServer.run(HttpServer.java:418)
Caused by: java.io.EOFException: End of input at line 1 column 8352906 path $..branchData.3[187].nodeLength
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:69)
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:61)
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        ... 8 more

**Comment by tntim96** [comment]
I think I need a copy of the source code (minimal example) or JSON to progress this.

**Comment by weiding111** [comment]
Could you please show me your email so I could send your the code?

**Comment by tntim96** [comment]
Just paste a minimal example here with nothing confidential in it (i.e. remove all the code except the part causing the error and rename as necessary).

**Comment by weiding111** [comment]
Is there any restriction for the folder depth of --document-root?

**Comment by tntim96** [comment]
Nothing that I've put in. It should be able to work to a large depth.

**Comment by tntim96** [comment]
>  Is there any difference about the jscover work logic between with --include-unloaded-js or without --include-unloaded-js when adding the branch related jscover code?

There will be a slight difference as the uncovered branches have to be calculated. The relevant code is [here](https://github.com/tntim96/JSCover/blob/master/src/main/java/jscover/instrument/UnloadedSourceProcessor.java#L380).

**Comment by weiding111** [comment]
I could not get any clue from the source code you mentioned.
The error contains "SEVERE,"Error saving coverage data",jscover.server.InstrumentingRequestHandler,
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 8727168 path $..branchData.3[441].evalFalse". So I think it should relate to the source code where adding "branchData" to js files or collecting and summary the branch data part into jacoverage.json.

**Comment by tntim96** [comment]
> So is there any relation between covered js files and unloaded js files when generate the branch data?

Yes. It's hard for me to debug the problem from that information. It would be helpful to isolate (and remove anything sensitive from) the JavaScript source code that is causing the problem.

**Comment by weiding111** [comment]
I would like to strip js source code that is causing the problem. But you know that, it is product, how could I know which Javascript that JSCover covered is caused this issue? I could know the source code not covered which is under --document-root dir, but I don't know which covered Javascript from product causing the problem. Now the issue is blocked here. The only way I could think about is there is origin-src under target folder which is generated automatically when enable "--include-unloaded-js",  the files under origin-src are the Javascript source code which covered, right? Could this issue be reproduced if with these origin-src from you side? Do you have any other idea to move this issue on?

**Comment by tntim96** [comment]
I see a couple of options:
1. Use a binary search to exclude different parts of the unloaded JavaScript to narrow down the source
1. Try instrumenting the JavaScript on the file system and deploy that to your system instead of using proxy mode. There's a working example [here](https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system).

I recommend trying option 2, because it's a more robust way to test anyway.

**Comment by weiding111** [comment]
just one doubt of the option 1.  There is no issue when I use "--include-unloaded-js" and the selenium tests does not launched the login page of the product. There are 3 situations here. 
1. with  "--include-unloaded-js", not login product page ---- no issue
2. no "--include-unloaded-js", login product page  -------no issue
3. "--include-unloaded-js" and login product page  ---the issue appears.

so the focus should be the relation between covered js files and unloaded js files when generate the branch data, I am not clear about the option 1. Please correct me if my understanding is wrong?
