### ISSUE TITLE
License Classpath Exception?

### ISSUE THREAD

**Issue by mandrachek** [tntim96/JSCover#271]
Would it be possible for you to include the GNU Classpath exception to your license?
https://www.gnu.org/software/classpath/license.html

Only with this license change (or a similarly permissive license like LGPL, etc.) would it be legitimate to embed JSCover in, for example, your selenium test suite, without having to license your test suite as GPL.

**Comment by tntim96** [comment]
I'm OK with the idea, but the [FAQ](https://www.gnu.org/software/classpath/faq/faq.html) seems to indicate that it's for the GNU JDK/JRE. Can you point me to any more documentation or examples where others use this?

I guess you just include a a file, e.g. `LICENSE-GNU-CLASSPATH.txt` in the JAR?

**Comment by tntim96** [comment]
Done. I've uploaded the SNAPSHOT.

**Comment by dinun** [comment]
Great idea this was introduced. @tntim96  Should not this file be updated with the classpath exception? https://github.com/tntim96/JSCover/blob/694c762508cc5b643221f4d08404fdb0f0b74873/LICENSE?

**Comment by tntim96** [comment]
Done. Thanks for the input.
