### ISSUE TITLE
Android mWeb that build on node js + ES6 Support?

### ISSUE THREAD

**Issue by ramkumary** [tntim96/JSCover#277]
I have used jscoverage long time ago and it was helpful. Now, We need to use this library for android mWeb which developed on node js + ES6? Currently, We are using appium framework to automate the mWeb scenarios which I need to capture the code coverage. I had checked Istanbul-middleware, Istanbul, But no luck. Any directions, please?

**Comment by tntim96** [comment]
Have you tried the Istanbul forums?
