### ISSUE TITLE
Run jscover scan for public website

### ISSUE THREAD

**Issue by lct005** [tntim96/JSCover#282]
I need to run JSCover via proxy-mode, and scan for public website.
Now, I'm able to scan web with localhost, but it failed when scan with public url (lets say: http://mywebtest.com).
It hang when I clicked to see Summary tab, and report was empty when I stored report.
How can I run that scenario?
Thanks

**Comment by tntim96** [comment]
Take a look at https://github.com/tntim96/JSCover-samples, and specifically the two tests under https://github.com/tntim96/JSCover-samples/tree/master/src/test/java/jscover/webdriver/proxy.

For any further help, you'd have to provide more details. Note that JSCover proxy mode doesn't work for SSL. In that case you'd need to pre-instrument the JavaScript on the public web-site and not use proxy-mode.

**Comment by lct005** [comment]
The option `--local-storage` helps solve the problem.
Thanks for the hint.
