### ISSUE TITLE
hi I can open my project in JSCover browser,But when I click Summary,It's empty, I can't get Coverage data

### ISSUE THREAD

**Issue by Kepler-ZZ** [tntim96/JSCover#289]
hi，I use file mode,when I instrument the js file,
 I can open my project in JSCover browser,
But when I click Summary,It's empty, I can't get Coverage data

![image](https://user-images.githubusercontent.com/66777432/84479291-4686de00-acc5-11ea-9943-2994447272ba.png)

**Comment by tntim96** [comment]
Hi @Kepler-ZZ , is there some way I can replicate this?

**Comment by zxf-nobug** [comment]
Hi @tntim96 ，I encountered the same problem，I follow the example given in the documentation to configure the proxy，When clicking the Summary menu, the page cannot jump to other pages （because js is not obtained），Is there more documentation to guide how to configure the proxy?

Best Regards
