### ISSUE TITLE
Proxy Server: Get request is not ending \r\n

### ISSUE THREAD

**Issue by abhinav1708** [tntim96/JSCover#302]
As per HTTP 1.0 standard, request lines should end with CR LF i.e. \r\n
https://www.w3.org/Protocols/HTTP/1.0/spec.html#Request-Line
Request-Line = Method SP Request-URI SP HTTP-Version CRLF

This was being followed in handleProxyPostOrPut but for Get request line was ended with \n
handleProxyRequest function line number 385
remotePrintWriter.print(method + " " + uri + " HTTP/1.0\n");

Because of this Get request was not working on some servers in proxy mode

Created a pull request to fix this issue https://github.com/tntim96/JSCover/pull/301

**Comment by abhinav1708** [comment]
Pull request for code fix
https://github.com/tntim96/JSCover/pull/301
#301

**Comment by tntim96** [comment]
Thanks for the fix. I'll do a new release soon.

**Comment by abhinav1708** [comment]
-

**Comment by abhinav1708** [comment]
Issue fixed
