### ISSUE TITLE
report file jscoverage.html is abnormal

### ISSUE THREAD

**Issue by lzf-bupt** [tntim96/JSCover#304]
Hello, when I use jscover-2.0.12 and execute the command "Java - jar target / dist / jscover-all.jar - WS -- document root = doc / example -- report dir = target", the coverage information can be displayed correctly, but the code coverage displayed in the jscoverage.html file exported to the target folder is always 0. Do you know how to solve this problem?
![image](https://user-images.githubusercontent.com/75766641/129337438-6f9fdaa5-c24c-4558-83b0-630a9b359a1d.png)

**Comment by lzf-bupt** [comment]
The screenshot of the test process is like this
![image](https://user-images.githubusercontent.com/75766641/129338223-ba070af0-a8ed-48d0-a897-4fd3f436faa1.png)

**Comment by tntim96** [comment]
This is probably a permissions issue, see the [FAQ](http://tntim96.github.io/JSCover/?page=faq.html) for information.

In short, Chrome needs to start with `--allow-file-access-from-files`. For FireFox set the `privacy.file_unique_origin` config option to false. Let me know what browser you're using and I'll see if it needs a similar security setting.

**Comment by lzf-bupt** [comment]
I use Google browser. I used your suggestion to start Google browser with the "chrome.exe --allow-file-access-from-files" command in the command line window, and then I used the "java -jar target/dist/JSCover-all.jar -ws --document-root=doc/example --report-dir=target" command. During the test, the code coverage information can be displayed correctly, but the code coverage is still 0 in the jscoverage.html file of the exported report.

**Comment by tntim96** [comment]
Is an error displayed in the dev-tools console?

**Comment by lzf-bupt** [comment]
When I start Google browser (Figure 1) with the "- allow file access from files" command, it cannot enter‘ https://localhost:8080/jscoverage.html ’. But now other browsers, such as edge browser (Figure 2)&nbsp;and Lenovo browser(Figure 3)&nbsp;, can access it‘ https://localhost:8080/jscoverage.html ’Interface





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tntim96/JSCover"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tntim96/JSCover] report file jscoverage.html is abnormal (#304)





 
Is an error displayed in the dev-tools console?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lzf-bupt** [comment]
When I start Google browser with the "- allow file access from files" command and 'java -jar target/dist/JSCover-all.jar -ws --document-root=doc/example --report-dir=target', it can  enter‘ https://localhost:8080/jscoverage.html ’, and sometimes it cannot enter  ‘https://localhost:8080/jscoverage.html '.

**Comment by lzf-bupt** [comment]
I changed from Google browser to Firefox browser, and the reports exported after “setting the 'privacy.file_unique_origin' config option to false” can be opened normally with Google browser. Thank you
