### ISSUE TITLE
The system becomes very slow

### ISSUE THREAD

**Issue by githubtestt** [tntim96/JSCover#313]
Our system front-end is a micro front-end. After compilation and installation, the system becomes very slow, and the response of each operation is more than 10 times slower than before. This is not the case for projects without front-end. Have you encountered it? How to fix it?

**Comment by tntim96** [comment]
I'm not sure I have enough context.

> After compilation and installation

Do you mean after instrumenting? It would be expected that counting all the line, function and branch hits would slow the JavaScript down  quite a bit.

**Comment by githubtestt** [comment]
The project is Micro-frontends framework, After instrumenting and deploying, Using software platform becomes very slow.

**Comment by tntim96** [comment]
As long as it's working it shouldn't matter. If it's too slow you can try [turning off branch and function coverage](http://tntim96.github.io/JSCover/manual/manual.xml#serverMode) with `--no-branch` and `--no-function`.
