### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by amrix08** [tntim96/JSCover#314]
For everyone's context, I'm browsing an apache web application that is being run on the port 10100, As per checking  the console on the browser, I've noticed that there was an error. Please see details be for your reference.

`Uncaught DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame`

How can I proceed with this? Now I'm stuck in the login loop. It keeps on refreshing upon typing the credentials and submitting it

![image](https://user-images.githubusercontent.com/62284865/160361331-687ca7aa-befe-41df-87a8-03566fd304fb.png)

**Comment by tntim96** [comment]
What version of JSCover are you using, and how are you instrumenting? It looks like you're using it as a proxy?

**Comment by amrix08** [comment]
JSCover 2.0.14 for the version. I used the simple web browser sever.

**Comment by tntim96** [comment]
So you can't really do it that way. You're best option is to instrument the files and put them on you web-server. There's an example of that here: https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system
