### ISSUE TITLE
How to skip some .js files while instrumenting the code?

### ISSUE THREAD

**Issue by nitin1502** [tntim96/JSCover#316]

**Comment by tntim96** [comment]
Checkout the [manual](http://tntim96.github.io/JSCover/manual/manual.xml)

For [server mode](http://tntim96.github.io/JSCover/manual/manual.xml#serverMode) there's `--no-instrument=URL` and `--no-instrument-reg=URL` which can be specified multiple times as well as `-only-instrument-reg=URL`.

The same options are also available for [file mode](http://tntim96.github.io/JSCover/manual/manual.xml#fileMode).
