### ISSUE TITLE
Any tips for https web server

### ISSUE THREAD

**Issue by angelikaYang** [tntim96/JSCover#317]
I wanna get the selenium tests coverage for js code of my https server project, but now the jscoverage proxy does not support https, any tips that I can do for this ?

**Comment by tntim96** [comment]
Given your scenario, it's best to instrument the JavaScript using file-mode, then run you tests as per normal on the server. There's an example at https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system
