### ISSUE TITLE
Extracting and saving coverage data using JSCover

### ISSUE THREAD

**Issue by shreyxskar** [tntim96/JSCover#318]
Hi,

My application runs on linux environment (RHEL) and I want to get the code coverage of JS files on same. For this I was able to instrument the JavaScript files on FS mode using below command:
`java -jar JSCover-all.jar -fs --no-instrument=/some/location SOURCE DESTINATION`

After this I'm not sure how to proceed with running tests on the instrumented code (Query 1). Also, for GUI webserver this application utilizes some other port apart from 8080 (let's say 76543)

Now, how can I use the instrumented code with my application since different port is involved? (Query 2)

Once my webserver runs with instrumented set of JS files then how can I get the report of coverage after running my automated tests that are written in Robot framework based in Python? (Query 3)

Please help with the above queries..

NOTE: In documentation, I saw we can get the report using the below command but I get this error:
`java -cp JSCover-all.jar jscover.report.Main --format=XMLSUMMARY ~/instrumented/code/location`

May 25, 2022 3:48:38 AM jscover.report.Main runMain
INFO: Args: --format=XMLSUMMARY,/root/instrumented
May 25, 2022 3:48:39 AM jscover.report.Main runMain
INFO: Starting JSCover 2.0.12 merge
Exception in thread "main" java.lang.RuntimeException: Problem loading file: '/root/instrumented/code/location/jscoverage.json'
        at jscover.util.IoUtils.loadFromFileSystem(IoUtils.java:482)
        at jscover.report.Main.saveXmlSummary(Main.java:458)
        at jscover.report.Main.runReport(Main.java:407)
        at jscover.report.Main.runMain(Main.java:394)
        at jscover.report.Main.main(Main.java:366)
Caused by: java.io.FileNotFoundException: /root/instrumented/code/location/jscoverage.json (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at jscover.util.IoUtils.loadFromFileSystem(IoUtils.java:479)
        ... 4 more

TIA

**Comment by tntim96** [comment]
> After this I'm not sure how to proceed with running tests on the instrumented code

Just deploy the instrumented files to wherever you run the tests, and then run the tests as usual. The coverage will automatically be collected.

If you're reloading pages, you can save the coverage between each page load with `--local-storage`. Once finished, you can collect the coverage with `window.jscoverage_serializeCoverageToJSON()`.

See the example at: https://github.com/tntim96/JSCover/tree/master/examples/localStorage-file-system

> In documentation, I saw we can get the report using the below command but I get this error:

The is for converting reports, not generating them. It's looking for `/root/instrumented/code/location/jscoverage.json` to convert.

**Comment by shreyxskar** [comment]
> If you're reloading pages, you can save the coverage between each page load with --local-storage. Once finished, you can collect the coverage with window.jscoverage_serializeCoverageToJSON().

For this, where shall I add these lines as all my tests are running in Python and in my machine, only NodeJS interpreter is available. In the example I saw this `window.jscoverage_serializeCoverageToJSON()` is available only in Webdriver, Selenium, HTMLUnit & PhantomJS.

Any suggestions to do this in Python/NodeJS?

**Comment by tntim96** [comment]
For a node project you could try [Istanbul](https://istanbul.js.org/)
