### ISSUE TITLE
JSCover merge result report

### ISSUE THREAD

**Issue by pataself** [tntim96/JSCover#72]
When I call the following JSCover-all to merge the result reports. java.lang.ClassCastException occurred 

java -cp JSCover-all.jar jscover.report.Main --merge C:\Report\result1 C:\Report\result2 C:\Report

Error Message:
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to org.mozilla.javascript.NativeObject
at jscover.report.JSONDataMerger.readBranchConditionJSONDataMerger.java:443
at jscover.report.JSONDataMerger.readBranchLinesJSONDataMerger.java:436
at jscover.report.JSONDataMerger.jsonToMapJSONDataMerger.java:420
at jscover.report.JSONDataMerger.mergeJSONCoverageStringJSONDataMerger.java:364
at jscover.report.Main.mergeReportsMain.java:408
at jscover.report.Main.runMainMain.java:392
at jscover.report.Main.mainMain.java:359

Do you guys know what could be wrong with this? Please help. thank you.

**Comment by shuyer520** [comment]
hello,  I got JSON data is null, the coverage result of JSON data as below:
{"/script.js":{"lineData":[null,0,0,null,0,0,null,0,0,0,0,null,0,0,null,0,0,null,0,0,null,0,0,0,0,0],"functionData":[0,0,0],"branchData":{"9":[null,{"position":0,"nodeLength":0,"evalFalse":0,"evalTrue":0}],"12":[null,{"position":0,"nodeLength":0,"evalFalse":0,"evalTrue":0}],"15":[null,{"position":0,"nodeLength":0,"evalFalse":0,"evalTrue":0}],"18":[null,{"position":0,"nodeLength":0,"evalFalse":0,"evalTrue":0}]}}}

My steps is:
1)Run file mode command: java -jar JSCover-1.1.0/target/dist/JSCover-all.jar -fs JSCover-1.1.0/doc/example Mytest --local-storage --include-unloaded-js
2)Start a non-instrumenting web-server to avoid browser-filesystem issues. The command was java -cp target\dist\JSCover-all.jar jscover.server.SimpleWebServer 8080
3)Open Firefox browser and navigate to http://localhost:8080/DESTINATION-DIRECTORY/jscoverage.html
4)Click "Open in window" button. (this will open a new tab)
5)in new tab, navigate to test page
6)Now when I open the jscoverage.json file ,the data is null, then coverage report can't be saved into the JSON file. Why? and How can I save the coverage data? Thank you , Looking forward to your answer

**Comment by tntim96** [comment]
The JSON file is created with all the unloaded JS from `--include-unloaded-js` switch.

You have to [retrieve the JSON from the browser](http://tntim96.github.io/JSCover/manual/manual.xml#fileSystemSave) and merge it with that JSON file.

**Comment by shuyer520** [comment]
Now if  I want to get the JSCover report by manual test my web page, not automation test or unit test.
How can get the JSON report? Thank you very much.

**Comment by shuyer520** [comment]
I run file mode command: java -jar JSCover-1.1.0/target/dist/JSCover-all.jar -fs JSCover-1.1.0/doc/example Mytest --local-storage , 
2)test my web UI page that the JS file has been instrumented by **manul testing**
3)Open the jscoverage.html , I can see the JS file coverage, but how can I store the coverage info by manul test to the json file(jscoverage.json)?

**Comment by tntim96** [comment]
In the browser, you can run `jscoverage_serializeCoverageToJSON()` in the developer console.

**Comment by shuyer520** [comment]
yeah,I get it, Thank you very much!!!
