### ISSUE TITLE
complete coverage of javascript coalesce

### ISSUE THREAD

**Issue by kellyselden** [tntim96/JSCover#86]
is it possible to get complete coverage of this line?

this.imageFactory = stuff.imageFactory || function() { return new Image() };

it's a hack of dependency injection. it's never evaluated to false, but the right-most is always true.

**Comment by eidng8** [comment]
It works. Thanks a lot.

btw, `--detect-coalesce` may be confusing. Wouldn't `--allow-coalesce` or `--ignore-branch-assign` be better? Or something else, sorry for my poor English. :smirk:

**Comment by tntim96** [comment]
Great.

Yes the naming is difficult, but it was the best I could think of that wasn't too long (e.g. `--ignore-branch-on-null-coalesce`). It's not exactly a branch but a condition, and other branch assignments won't be ignored, so I thought I'd just keep it short a leave the description in the manual and help documentation.
